interface ReviewedPractice {
  question: string
  hint: string
  answer: string
  marks: number
}

type PracticeSeed = [question: string, answer: string, marks?: number, hint?: string]

const geographyHint = 'Use accurate geographical vocabulary, develop cause-and-effect links and add named evidence where the question requires it.'
const businessHint = 'Apply the concept to the business context, develop the impact and support any judgement.'
const designHint = 'Link the technical choice to the user and specification, then justify it with properties, evidence or a measurable test.'

function entries(hint: string, seeds: Record<string, PracticeSeed>): Record<string, ReviewedPractice> {
  return Object.fromEntries(Object.entries(seeds).map(([id, [question, answer, marks = 6, customHint]]) => [id, {
    question, answer, marks, hint: customHint ?? hint,
  }]))
}

const geography = entries(geographyHint, {
  'geo-hazards-risk': ['Explain why rapid urbanisation can increase hazard risk.', 'Rapid urbanisation can put more people and valuable infrastructure in exposed locations such as unstable slopes or floodplains. When growth outpaces building control and emergency services, informal housing is less resistant and evacuation or recovery is harder. The hazard itself may be unchanged, but vulnerability and exposure increase the risk of disaster.'],
  'geo-hazards-tectonic': ['Explain why the effects of earthquakes differ between places.', 'Effects depend on magnitude, depth and distance from the epicentre, but also on vulnerability and capacity to cope. Strong building codes, monitoring, emergency services and insurance can reduce deaths and speed recovery. In a lower-income setting, weaker buildings and limited medical or transport capacity can turn a similar physical event into a greater human disaster.'],
  'geo-hazards-weather': ['Explain how a tropical storm forms and strengthens.', 'Tropical storms develop over ocean water above about 27°C, where evaporation supplies warm, moist air. Rising air condenses, releasing latent heat that powers further uplift and falling pressure. Air is drawn in and spirals because of the Coriolis effect; the storm strengthens while it remains over deep warm water but weakens over land or cooler water.'],
  'geo-hazards-climate': ['Assess whether mitigation or adaptation is the better response to climate change.', 'Mitigation tackles causes: renewable energy, afforestation and carbon capture can reduce future warming, but require coordinated long-term action. Adaptation such as flood defences, drought-resistant crops and water management reduces current vulnerability but does not stop warming. The strongest judgement is conditional: both are required, with rapid mitigation limiting future costs while adaptation protects places from unavoidable change.', 9],
  'geo-ecosystems': ['Explain how a change to one component of an ecosystem can affect the whole system.', 'Components are interdependent. Removing a predator can increase prey numbers, causing heavier grazing and less vegetation. Reduced plant cover can lower interception, increase runoff and soil erosion, and reduce nutrient stores. A single population change can therefore alter food webs, water flows and nutrient cycling.'],
  'geo-rainforests': ['Evaluate one strategy for managing tropical rainforests sustainably.', 'Selective logging removes chosen mature trees rather than clearing an entire area, retaining much of the canopy, habitat and nutrient cycle. Replanting and long rotation periods can support recovery while timber provides income. However, access roads may encourage further clearance and enforcement can be weak, so success depends on monitoring, local participation and controlled demand.', 9],
  'geo-hot-deserts': ['Explain how plants are adapted to hot-desert conditions.', 'Succulents store water in fleshy tissues, while waxy surfaces and reduced leaves limit transpiration. Deep tap roots reach groundwater and widespread shallow roots absorb brief rainfall quickly. Some plants remain dormant as seeds until rain. These adaptations address both very low rainfall and high evaporation.'],
  'geo-cold-environments': ['Explain why cold environments are vulnerable to development.', 'Low temperatures make plant growth and soil formation very slow, so damaged vegetation can take decades to recover. Permafrost can thaw when surfaces are disturbed, destabilising roads and buildings and releasing carbon. Food webs are relatively simple, so disruption to one species can spread. Remoteness also makes spill response and restoration difficult.'],
  'geo-uk-overview': ['Explain how geology contributes to differences between UK upland and lowland landscapes.', 'More resistant rocks erode slowly and often form higher, steeper uplands, especially in the north and west. Less resistant sedimentary rocks are worn down more easily, contributing to gentler lowlands in much of the south and east. Geological structure also influences drainage, slopes and the location of river valleys.'],
  'geo-coasts': ['Explain how a headland and bay coastline develops.', 'Bands of resistant and less resistant rock exposed to waves erode at different rates. Softer rock retreats rapidly to form bays, while harder rock remains as headlands. Wave refraction concentrates energy on projecting headlands and lowers energy in sheltered bays, reinforcing erosion of the headland and deposition of beach material in the bay.'],
  'geo-rivers': ['Explain why flood risk changes after urbanisation.', 'Impermeable roads and roofs reduce infiltration and increase surface runoff. Drains transfer water rapidly to the channel, shortening lag time and raising peak discharge on a storm hydrograph. Building on floodplains also increases exposure. Sustainable drainage, permeable surfaces and storage ponds can slow the transfer and reduce the peak.'],
  'geo-glacial': ['Explain how a corrie forms.', 'Snow accumulates in a sheltered hollow and compresses into ice. Rotational movement causes abrasion to deepen the basin, while plucking steepens the back wall. Freeze-thaw weathering supplies debris and weakens rock. Less erosion at the front leaves a rock lip, and after melting the hollow may contain a tarn.'],
  'geo-urban': ['Evaluate one strategy used to make a city more sustainable.', 'An integrated public-transport system can reduce car journeys, congestion and air pollution while improving access to work and services. Its impact is greater when services are affordable, frequent and linked to walking or cycling. Construction is costly and benefits may be uneven, so a supported judgement should compare measured environmental gains with accessibility and funding.', 9],
  'geo-economic': ['Explain how a transnational corporation can bring both opportunities and challenges to a newly emerging economy.', 'A TNC can create direct and supply-chain jobs, pay taxes, train workers and improve infrastructure or export earnings. However, profits may leave the host country, higher-paid jobs may go to skilled outsiders and weak regulation can allow low wages or pollution. The balance depends on local sourcing, regulation, tax arrangements and working standards.'],
  'geo-resources-overview': ['Explain why resource security varies between places.', 'Supply depends on climate, geology, land, technology and infrastructure, while demand rises with population and income. Wealthier states can import resources or invest in storage and treatment; poorer or landlocked regions may lack access even where physical supply exists. Security therefore reflects affordability and distribution as well as total availability.'],
  'geo-resource-food': ['Assess whether increasing food supply through large-scale technology is sustainable.', 'Irrigation, mechanisation and high-yield crops can raise output quickly, but may cause soil salinisation, water depletion, chemical pollution or dependence on expensive inputs. Smaller-scale appropriate technology may protect soils and local control but produce less immediate output. Sustainability depends on long-term yields, water use, affordability and who receives the food.', 9],
  'geo-resource-water': ['Evaluate a large-scale water-transfer scheme.', 'A transfer can supply homes, farms and industry in deficit regions and support economic development. Dams and canals are costly, displace people, alter river ecosystems and may create conflict with donor regions. A judgement should compare the reliability and scale of supply with environmental and social costs and consider whether conservation or local recycling could reduce demand.', 9],
  'geo-resource-energy': ['Evaluate the use of renewable energy to improve energy security.', 'Renewables diversify supply and reduce dependence on imported fossil fuels, while operational emissions are low. Wind and solar output is intermittent and may require storage, backup generation and grid investment; projects can also affect landscapes or habitats. A mixed system matched to local conditions is usually more secure than relying on one source.', 9],
  'geo-issue-evaluation': ['A pre-release option creates jobs but damages a habitat. Explain how you would reach a justified decision.', 'Identify the decision criteria, including employment, cost, distribution of benefits, carbon, biodiversity and reversibility. Test stakeholder claims against mapped and numerical evidence, distinguish short- from long-term effects and compare feasible alternatives. The conclusion should select an option, acknowledge its main cost and explain why the chosen evidence makes it preferable.'],
  'geo-fieldwork': ['Explain how a fieldwork enquiry could be improved after using convenience sampling.', 'Convenience sampling may overrepresent easy-to-reach sites and produce a biased pattern. A systematic sample at fixed intervals would improve spatial coverage, or a stratified sample could represent different zones. Repeating measurements at different times, standardising the method and increasing sample size would improve reliability; the best change must match the enquiry question.'],
  'geo-skills': ['On a 1:25,000 map two points are 6.4 cm apart. Calculate the ground distance in kilometres and state one limitation of this measurement.', '6.4 × 25,000 = 160,000 cm, which is 1,600 m or 1.6 km. A straight-line measurement may underestimate a winding route; measuring along the route with string or segmented lines would give a closer value.', 4],
})

const business = entries(businessHint, {
  'business-1-1-enterprise': ['A café introduces pre-ordering after customers complain about queues. Analyse how this idea could add value.', 'Pre-ordering adds convenience by reducing waiting time, so busy customers may prefer the café and be willing to buy more often or pay a small premium. Higher demand could raise revenue and differentiate the café. However, the value gained depends on reliable technology and whether setup and staffing costs are lower than the extra contribution.'],
  'business-1-2-opportunity': ['A start-up surveys only its social-media followers before launching a product for all teenagers. Analyse one limitation.', 'Followers already interested in the business are unlikely to represent all teenagers, creating sampling bias. Results may exaggerate demand and lead the start-up to order too much stock. A larger stratified sample across ages, locations and non-followers, supported by secondary market data, would reduce but not eliminate uncertainty.'],
  'business-1-3-finance': ['A business sells 800 units at £12. Variable cost is £7 per unit and fixed costs are £3,000. Calculate profit and margin of safety if break-even output is 600 units.', 'Revenue = 800 × £12 = £9,600. Variable cost = 800 × £7 = £5,600, so total cost = £8,600 and profit = £1,000. Margin of safety = actual output 800 − break-even output 600 = 200 units.', 6],
  'business-1-4-effective': ['Justify whether a new takeaway should operate as a franchise.', 'A franchise supplies a known brand, operating model and training, reducing start-up risk and helping demand. In return, the owner pays fees, shares revenue and has less control over menu or promotion. Franchising is preferable if the entrepreneur values support and can fund the fees; an original independent concept may be better if local differentiation and control are central.', 9],
  'business-1-5-external': ['Analyse how a rise in interest rates could affect a small furniture business.', 'Existing variable-rate loans and new borrowing may cost more, raising expenses and reducing profit or investment. Customers using credit may cut spending on furniture, lowering demand. The scale depends on the firm’s debt, customers’ incomes and whether it can delay investment, find fixed-rate finance or shift toward lower-priced products.'],
  'business-2-1-growth': ['Evaluate whether a successful UK clothing business should expand internationally through e-commerce.', 'E-commerce gives access to larger markets without funding many stores and can spread risk across countries. The business faces delivery and returns costs, exchange-rate changes, local competition and the need to adapt promotion or sizing. Expansion is justified if research shows sufficient demand and contribution after logistics; a limited market trial reduces risk.', 12],
  'business-2-2-marketing': ['A premium bicycle brand cuts price while increasing expensive influencer promotion. Analyse the possible conflict in its marketing mix.', 'A lower price may increase sales but can weaken the premium positioning communicated by the product design and promotion. High promotional spending also reduces profit per unit unless volume rises enough. The mix could work for a new segment, but the firm should ensure price still signals quality and that targeted promotion reaches customers able to value the product.'],
  'business-2-3-operations': ['Justify whether a growing bakery should change from batch to flow production.', 'Flow production can produce high volume at low unit cost with consistent quality, helping the bakery supply supermarkets. It requires expensive equipment, predictable demand and standard products, and a breakdown can stop the line. It is suitable if demand is high and stable; batch production remains better for variety and seasonal orders.', 9],
  'business-2-4-finance': ['A firm has revenue of £500,000, cost of sales of £300,000 and expenses of £150,000. Calculate gross and net profit margins.', 'Gross profit = £500,000 − £300,000 = £200,000, so gross profit margin = £200,000 ÷ £500,000 × 100 = 40%. Net profit = £200,000 − £150,000 = £50,000, so net profit margin = £50,000 ÷ £500,000 × 100 = 10%.', 6],
  'business-2-5-people': ['Evaluate whether financial rewards are the best way to improve employee motivation.', 'Performance pay or bonuses can focus effort and attract staff, especially where output is measurable. They raise costs and may encourage quantity over quality or unhealthy competition. Training, recognition, responsibility and job enrichment may create longer-term commitment. The best method depends on employee needs, the task and whether performance can be measured fairly.', 9],
})

const designTechnology = entries(designHint, {
  'dt-emerging': ['Evaluate the use of collaborative robots in a small manufacturing business.', 'Robots can repeat precise tasks safely, improve consistency and work alongside staff, while reprogramming supports flexible production. Purchase, maintenance and training are costly and some roles may change or disappear. Adoption is justified where measurable quality, safety and output gains repay the investment and workers are trained for higher-skill tasks.', 9],
  'dt-energy': ['Justify an energy system for a remote emergency light.', 'A rechargeable battery combined with a small solar panel provides stored energy when light is needed and can recharge without a grid connection. Capacity must cover the required operating time and the panel must suit local light levels. The design should also consider battery lifespan, charge control, weather protection and responsible end-of-life disposal.'],
  'dt-new-materials': ['Explain why a shape-memory alloy could be selected for an actuator.', 'A shape-memory alloy returns to a preset form when heated, converting thermal or electrical energy into controlled movement with few moving parts. It can make a compact, quiet actuator. The designer must account for response time, fatigue, cost, operating temperature and whether the movement and force meet the specification.'],
  'dt-systems': ['Describe a control system for a greenhouse fan.', 'A temperature sensor provides the input to a programmable controller. The controller compares the reading with a threshold and sends an output through a driver to the fan motor; feedback provides updated temperature readings. Hysteresis should be programmed so the fan does not switch rapidly near the threshold.'],
  'dt-mechanisms': ['A hand crank must turn a shaft three times faster. Propose and justify a gear arrangement.', 'Use a large driver gear on the crank meshing with a driven gear having one third as many teeth. The speed ratio makes the output rotate three times for each input turn, although output torque falls. Exact tooth counts should avoid undercutting and the design needs aligned shafts, secure bearings and a guard.'],
  'dt-materials-overview': ['Select and justify a material for a reusable outdoor sign.', 'A weather-resistant material such as UV-stabilised acrylic could provide a smooth printable surface, colour options and water resistance. Thickness should provide stiffness without excessive mass or cost. The decision must also compare impact resistance, scratching, manufacture, repair and end-of-life recycling with alternatives such as aluminium composite or treated timber.'],
  'dt-selection-forces': ['Explain how a shelf can be redesigned to resist bending.', 'Increasing section depth raises stiffness more effectively than simply adding width. A folded or I-shaped section places material away from the neutral axis, while ribs or a central support reduce deflection. The choice should be tested under the specified load and balanced against material use, appearance and manufacture.'],
  'dt-footprint-origins': ['Use life-cycle thinking to compare virgin aluminium with recycled aluminium for a product.', 'Virgin aluminium requires mining, refining and energy-intensive electrolysis, creating major embodied energy and habitat impacts. Recycled aluminium retains useful properties and uses much less processing energy, although collection, sorting and remelting still have impacts. The decision should also include product lifespan, transport, repair and recovery at end of life.'],
  'dt-working-materials': ['Justify a shaping process for producing 500 identical polymer cases.', 'Injection moulding gives repeatable complex forms, fine detail and low unit cost at medium-to-high volume. A metal mould and machine setup are expensive, so 500 units may only justify it if the case is complex or production will continue. Vacuum forming or additive manufacture could have lower tooling cost but different detail, waste and finishing requirements.'],
  'dt-production': ['Explain why batch production could suit 2,000 school planners.', 'A batch can be completed through each printing, cutting and binding stage using the same setup, giving consistency and a lower unit cost than one-off production. It still allows a later batch to use a different school design. The manufacturer must plan stock, storage, quality sampling and changeover time.'],
  'dt-processes-quality': ['Propose a measurable quality-control check for a drilled component.', 'Use a go/no-go gauge or callipers at planned inspection points to check the hole diameter against stated upper and lower tolerances. Record results so drift can be identified before a whole batch is defective. The gauge, sampling frequency and corrective action must be defined rather than relying on visual inspection alone.'],
  'dt-investigation': ['Explain how research for an inclusive school-bag design should be conducted.', 'Interview and observe a varied sample of pupils, including users with mobility or sensory needs, and measure loads and access tasks. Analyse existing products and ergonomic guidance, while protecting consent and privacy. Triangulating qualitative comments with measured data helps turn genuine needs into design opportunities.'],
  'dt-brief-specification': ['Write three measurable specification points for a reusable lunch container.', 'Capacity must be 900 ± 20 ml so it holds the target meal; the closed container must show no leakage after being inverted for two minutes; and external surfaces must remain below a specified safe temperature when filled with hot food. Each criterion is user-linked and testable, unlike vague terms such as attractive or strong.', 6],
  'dt-ideas': ['Explain how modelling reduces design fixation.', 'Quick sketches and low-cost physical or digital models let a designer generate and compare several genuinely different mechanisms, layouts or forms before committing. User feedback exposes assumptions early, and combining the best tested features encourages iteration. Recording rejected alternatives also shows why the selected concept answers the brief better.'],
  'dt-development': ['A prototype handle is uncomfortable for smaller users. Explain a strong development cycle.', 'Collect measured grip data and specific user feedback, then change diameter, profile or material while keeping other variables controlled. Produce a revised model and repeat the same comfort, slip and load tests with representative users. Compare results against the specification and document why evidence supports the next iteration.'],
  'dt-making': ['Explain how a maker can improve accuracy and reduce waste when producing repeated parts.', 'Plan a cutting list and nest parts on standard stock before cutting. Mark from a common datum and use a template or jig so dimensions and hole positions repeat consistently. Allow for kerf or seam allowance, check the first part against tolerances, and correct the setup before processing the batch.'],
  'dt-evaluation': ['Evaluate a prototype against the statement “it works well”.', 'The statement is too vague. Test each measurable specification criterion under realistic conditions, record quantitative results and gather representative user feedback. Compare results with targets, identify failure causes and prioritise improvements by safety and user impact. A credible evaluation distinguishes evidence from opinion and considers manufacture, sustainability and commercial viability.', 9],
})

const CONFIRMED_COURSE_PRACTICE: Record<string, ReviewedPractice> = {
  ...geography,
  ...business,
  ...designTechnology,
}

export function confirmedCoursePracticeFor(topicId: string): ReviewedPractice | null {
  return CONFIRMED_COURSE_PRACTICE[topicId] ?? null
}
