import { confirmedCoursePracticeFor } from './confirmed-course-practice'

export interface ReviewedPractice {
  question: string
  hint: string
  answer: string
  marks: number
}

const mathsHint = 'Show every important step and check that the final answer is reasonable.'
const scienceHint = 'Use precise scientific vocabulary and develop each link in your reasoning.'
const historyHint = 'Use precise knowledge and explain how it supports the command word.'

function practice(question: string, answer: string, marks = 4, hint = mathsHint): ReviewedPractice {
  return { question, hint, answer, marks }
}

export const REVIEWED_PRACTICE: Record<string, ReviewedPractice> = {
  // AQA Mathematics 8300 Higher
  'maths-number-structure': practice('Put −0.7, 2/3, −3/4 and 0.68 in ascending order.', 'Convert to decimals: −3/4 = −0.75 and 2/3 = 0.666…. Therefore −3/4 < −0.7 < 2/3 < 0.68.', 3),
  'maths-number-calculation': practice('Calculate 18 − 3 × (4 + 2)² ÷ 6. Show the order of operations.', '(4 + 2)² = 36. Then 3 × 36 ÷ 6 = 18, so 18 − 18 = 0.', 3),
  'maths-number-powers': practice('Write 360 as a product of prime factors and use it to find the HCF of 360 and 168.', '360 = 2³ × 3² × 5 and 168 = 2³ × 3 × 7. The shared prime powers are 2³ × 3, so the HCF is 24.', 5),
  'maths-number-fdp': practice('Write 0.2 recurring as a fraction in its simplest form.', 'Let x = 0.222…. Then 10x = 2.222…. Subtracting gives 9x = 2, so x = 2/9.', 3),
  'maths-number-accuracy': practice('A rectangle is measured as 8.4 cm by 5.2 cm, each correct to the nearest 0.1 cm. Find the upper bound for its area.', 'The upper bounds are 8.45 cm and 5.25 cm. The upper bound for the area is 8.45 × 5.25 = 44.3625 cm².', 3),
  'maths-number-standard-surds': practice('Simplify √72 and rationalise 5/√2.', '√72 = √(36 × 2) = 6√2. Also 5/√2 × √2/√2 = 5√2/2.', 4),
  'maths-algebra-manipulation': practice('Simplify (x² − 9)/(x² + 5x + 6). State any excluded values.', 'Factorise to (x − 3)(x + 3)/[(x + 2)(x + 3)]. This simplifies to (x − 3)/(x + 2), with x ≠ −3 and x ≠ −2.', 4),
  'maths-algebra-equations': practice('Solve 2x² − 7x + 3 = 0.', 'Factorise: (2x − 1)(x − 3) = 0. Therefore x = 1/2 or x = 3.', 3),
  'maths-algebra-simultaneous': practice('Solve y = x + 1 and y = x² − 5.', 'Equate the expressions: x² − 5 = x + 1, so x² − x − 6 = 0. Factorising gives (x − 3)(x + 2) = 0. Thus (x, y) = (3, 4) or (−2, −1).', 5),
  'maths-algebra-inequalities': practice('Solve x² − x − 6 < 0.', 'Factorise to (x − 3)(x + 2) < 0. The quadratic is negative between its roots, so −2 < x < 3.', 3),
  'maths-algebra-sequences': practice('The sequence 3, 8, 15, 24, 35 has a quadratic nth term. Find it.', 'First differences are 5, 7, 9, 11, so the second difference is 2 and the n² coefficient is 1. Comparing n² gives differences 2, 4, 6, 8, 10, so add 2n. The nth term is n² + 2n.', 4),
  'maths-algebra-graphs': practice('Find the equation of the line through (−2, 5) and (4, −7).', 'The gradient is (−7 − 5)/(4 − (−2)) = −12/6 = −2. Using y = mx + c and (−2, 5): 5 = 4 + c, so c = 1. The equation is y = −2x + 1.', 4),
  'maths-algebra-functions': practice('Let f(x) = 3x − 4 and g(x) = x². Find fg(2), gf(2) and f⁻¹(x).', 'fg(2) = f(4) = 8. gf(2) = g(2) = 4 because f(2) = 2. For the inverse, y = 3x − 4 gives x = (y + 4)/3, so f⁻¹(x) = (x + 4)/3.', 5),
  'maths-ratio-proportion': practice('Share £420 in the ratio 3:4:5.', 'There are 12 parts, so each part is £420 ÷ 12 = £35. The shares are £105, £140 and £175.', 3),
  'maths-ratio-percentages': practice('After a 20% increase, a price is £96. Find the original price.', 'The final price represents 120% of the original. £96 ÷ 1.2 = £80.', 2),
  'maths-ratio-direct-inverse': practice('y is inversely proportional to x². When x = 3, y = 8. Find y when x = 6.', 'y = k/x². Using x = 3 gives 8 = k/9, so k = 72. When x = 6, y = 72/36 = 2.', 4),
  'maths-ratio-rates': practice('A car travels 150 km in 2 hours 30 minutes. Calculate its average speed in m/s.', '2 hours 30 minutes = 2.5 hours, so the speed is 150 ÷ 2.5 = 60 km/h. Divide by 3.6 to convert: 60 ÷ 3.6 = 16.7 m/s to 3 significant figures.', 4),
  'maths-geometry-angles': practice('The exterior angle of a regular polygon is 24°. Find the number of sides and each interior angle.', 'Number of sides = 360 ÷ 24 = 15. Each interior angle is 180 − 24 = 156°.', 3),
  'maths-geometry-measures': practice('A sector has radius 9 cm and angle 80°. Find its area in terms of π.', 'Area = 80/360 × π × 9² = 18π cm².', 3),
  'maths-geometry-transformations': practice('Describe fully the transformation that maps (x, y) to (−2x, −2y).', 'It is an enlargement with centre (0, 0) and scale factor −2. The negative factor places the image on the opposite side of the centre.', 2),
  'maths-geometry-constructions': practice('Point P is on a bearing of 065° from A. Explain how to construct the direction accurately.', 'Draw a north line at A. Measure 65° clockwise from north using a protractor, then draw the ray from A in that direction. A bearing must use three figures.', 3),
  'maths-geometry-circles': practice('AB is a diameter of a circle and C is on the circumference. Angle BAC is 34°. Find angle ABC and justify every step.', 'Angle ACB is 90° because the angle in a semicircle is a right angle. Angles in a triangle total 180°, so angle ABC = 180 − 90 − 34 = 56°.', 3),
  'maths-geometry-similarity': practice('Two similar solids have corresponding lengths in the ratio 2:5. The smaller volume is 64 cm³. Find the larger volume.', 'The volume scale factor is (5/2)³ = 125/8. The larger volume is 64 × 125/8 = 1000 cm³.', 3),
  'maths-geometry-trig': practice('A triangle has sides 7 cm and 10 cm with an included angle of 48°. Find its area.', 'Area = 1/2 ab sin C = 1/2 × 7 × 10 × sin 48° = 26.0 cm² to 3 significant figures.', 3),
  'maths-probability-basics': practice('A biased coin lands heads with probability 0.62. It is tossed 250 times. Find the expected number of tails.', 'P(tails) = 1 − 0.62 = 0.38. The expected number is 250 × 0.38 = 95.', 2),
  'maths-probability-combined': practice('A bag contains 3 red and 7 blue counters. Two are taken without replacement. Find P(two red).', 'P(two red) = 3/10 × 2/9 = 6/90 = 1/15.', 3),
  'maths-statistics-sampling': practice('A school surveys the first 50 pupils entering the library about reading habits. Explain two limitations and improve the method.', 'Library users are likely to read more than the whole school, so the location creates selection bias. The first 50 may also overrepresent pupils arriving at one time. Use a random or stratified sample from the complete school roll instead.', 4),
  'maths-statistics-represent': practice('A histogram class 20 < x ≤ 30 has frequency 45 and class width 10. Find its frequency density and explain what bar area represents.', 'Frequency density = 45 ÷ 10 = 4.5. In a histogram, each bar area represents frequency, not the bar height alone.', 3),
  'maths-statistics-interpret': practice('Set A has median 42 and IQR 8. Set B has median 39 and IQR 15. Compare the distributions.', 'Set A has the higher typical value because its median is greater. It is also more consistent because its interquartile range is smaller. No conclusion about the full ranges can be made from this information.', 3),

  // AQA Combined Science: Trilogy 8464 Higher
  'science-b-cell': practice('A cell image is 36 mm wide and the real cell is 60 μm wide. Calculate the magnification.', 'Convert 36 mm to 36,000 μm. Magnification = image size ÷ real size = 36,000 ÷ 60 = ×600.', 3, scienceHint),
  'science-b-organisation': practice('Explain how the structure of an artery is adapted to its function.', 'Arteries carry blood away from the heart at high pressure. Their thick muscular and elastic walls withstand the pressure and stretch and recoil to maintain it. A relatively small lumen helps maintain pressure, and the smooth lining reduces friction.', 4, scienceHint),
  'science-b-infection': practice('Explain why antibiotics do not cure influenza and why unnecessary antibiotic use is harmful.', 'Influenza is caused by a virus, which reproduces inside host cells and lacks the bacterial structures targeted by antibiotics. Unnecessary use creates selection pressure: resistant bacteria survive, reproduce and spread, making future bacterial infections harder to treat.', 4, scienceHint),
  'science-b-bioenergetics': practice('Explain why the rate of photosynthesis stops increasing at very high light intensity.', 'At low light intensity, light is the limiting factor, so increasing it raises the rate. At high intensity another factor, such as carbon dioxide concentration or temperature, becomes limiting, so extra light cannot increase the rate further.', 4, scienceHint),
  'science-b-homeostasis': practice('Explain how negative feedback controls blood glucose after a carbohydrate-rich meal.', 'Blood glucose rises, so the pancreas releases insulin. Insulin causes body cells to take up glucose and the liver and muscles to convert glucose to glycogen. Blood glucose falls towards the normal level, reducing insulin release.', 4, scienceHint),
  'science-b-inheritance': practice('Two heterozygous parents have genotype Ff. Use a genetic cross to find the probability of an ff child.', 'The possible offspring are FF, Ff, Ff and ff. One of four is ff, so the probability is 1/4 or 25%. Genotype and phenotype should not be confused.', 4, scienceHint),
  'science-b-ecology': practice('Explain how removing a top predator can affect an ecosystem.', 'Its prey may increase because predation falls. The larger prey population may consume more organisms at the next trophic level, reducing them and altering competition. This trophic cascade can change biodiversity across the community.', 4, scienceHint),
  'science-c-atomic': practice('Explain why Group 1 metals become more reactive down the group.', 'Atoms have more occupied shells down the group, so the outer electron is further from the nucleus and more shielded. The nuclear attraction is weaker, making the electron easier to lose.', 4, scienceHint),
  'science-c-bonding': practice('Explain why graphite conducts electricity but diamond does not.', 'In graphite each carbon forms three covalent bonds, leaving one delocalised electron per atom that can move through the structure and carry charge. In diamond each carbon forms four bonds, so there are no delocalised electrons.', 4, scienceHint),
  'science-c-quantitative': practice('Calculate the mass of magnesium oxide formed when 4.8 g of magnesium burns completely. Ar: Mg = 24, O = 16.', 'Mg + 1/2O₂ → MgO. Moles of Mg = 4.8/24 = 0.20 mol, so 0.20 mol MgO forms. Mr(MgO) = 40, giving mass = 0.20 × 40 = 8.0 g.', 4, scienceHint),
  'science-c-changes': practice('Predict the products at each electrode during electrolysis of aqueous sodium chloride and explain why.', 'Hydrogen forms at the cathode because sodium is more reactive than hydrogen, so hydrogen ions/water are reduced instead. Chlorine forms at the anode because chloride ions are present and are oxidised to chlorine molecules.', 4, scienceHint),
  'science-c-energy': practice('Mean bond energies are H–H 436, Cl–Cl 243 and H–Cl 431 kJ/mol. Calculate the energy change for H₂ + Cl₂ → 2HCl.', 'Energy to break bonds = 436 + 243 = 679 kJ/mol. Energy released forming bonds = 2 × 431 = 862 kJ/mol. ΔH = 679 − 862 = −183 kJ/mol, so the reaction is exothermic.', 4, scienceHint),
  'science-c-rates': practice('Explain using collision theory why increasing temperature increases reaction rate.', 'Particles have more kinetic energy, so they move faster and collide more often. A greater proportion of collisions also have energy equal to or greater than the activation energy, so there are more successful collisions per second.', 4, scienceHint),
  'science-c-organic': practice('Explain why long-chain hydrocarbons are cracked and give the products.', 'Long-chain hydrocarbons are less useful and demand for shorter fuels and alkenes is higher. Cracking vaporises a hydrocarbon and passes it over a hot catalyst, producing shorter alkanes and alkenes. Alkenes can make polymers.', 4, scienceHint),
  'science-c-analysis': practice('A chromatogram gives a substance distance of 4.2 cm and solvent-front distance of 7.0 cm. Calculate Rf and explain one use.', 'Rf = distance moved by substance ÷ distance moved by solvent = 4.2/7.0 = 0.60. Under the same conditions, this can be compared with known values to help identify a substance.', 3, scienceHint),
  'science-c-atmosphere': practice('Explain how increasing atmospheric carbon dioxide can lead to climate change.', 'Carbon dioxide absorbs outgoing long-wave infrared radiation emitted by Earth and re-emits it in all directions. More energy is retained in the atmosphere, increasing average global temperature and changing climate patterns.', 4, scienceHint),
  'science-c-resources': practice('Evaluate recycling aluminium rather than extracting it from its ore.', 'Recycling uses much less energy than electrolysis, reducing fossil-fuel use and emissions. It also conserves finite ore and reduces mining waste. Collection, sorting and transport still use energy, and contamination can reduce product quality.', 4, scienceHint),
  'science-p-energy': practice('A 1200 W kettle runs for 150 seconds. Calculate the energy transferred in joules and kWh.', 'E = Pt = 1200 × 150 = 180,000 J. In kW and hours: 1.2 × (150/3600) = 0.050 kWh.', 4, scienceHint),
  'science-p-electricity': practice('A 12 V component carries 0.40 A for 5 minutes. Calculate its resistance and energy transferred.', 'R = V/I = 12/0.40 = 30 Ω. Time = 300 s and power = VI = 4.8 W, so E = Pt = 4.8 × 300 = 1440 J.', 5, scienceHint),
  'science-p-particles': practice('A metal block has mass 540 g and volume 200 cm³. Calculate its density in kg/m³.', 'Density = 540/200 = 2.7 g/cm³. Since 1 g/cm³ = 1000 kg/m³, the density is 2700 kg/m³.', 4, scienceHint),
  'science-p-atomic': practice('A radioactive sample has a count rate of 640 counts per minute and a half-life of 6 hours. Find its count rate after 18 hours.', '18 hours is three half-lives. The count halves three times: 640 → 320 → 160 → 80 counts per minute.', 3, scienceHint),
  'science-p-forces': practice('A 1200 kg car increases speed from 8 m/s to 20 m/s in 6 s. Calculate its acceleration and resultant force.', 'Acceleration = (20 − 8)/6 = 2.0 m/s². Resultant force = ma = 1200 × 2.0 = 2400 N.', 4, scienceHint),
  'science-p-waves': practice('A wave has frequency 250 Hz and wavelength 1.36 m. Calculate its speed and explain what changes when it enters another medium.', 'v = fλ = 250 × 1.36 = 340 m/s. Frequency remains fixed by the source; if speed changes in the new medium, wavelength changes proportionally and the wave may refract.', 4, scienceHint),
  'science-p-magnetism': practice('Explain how increasing current affects the force on a current-carrying wire in a magnetic field.', 'The magnetic field around the wire becomes stronger, so its interaction with the external magnetic field produces a larger force. Quantitatively F = BIL when the wire is perpendicular, so force is proportional to current.', 4, scienceHint),

  // AQA English Language 8700: original mini-sources and tasks
  'english-language-p1-q1': practice('Read: “Mara tightened her coat, checked the empty platform and watched the final train disappear into fog.” List four explicit details.', 'Valid details are: Mara tightens her coat; she checks the platform; the platform is empty; she watches a train; it is the final train; the train disappears; there is fog. Any four distinct details earn four marks.', 4, 'Select only information explicitly stated; do not infer.'),
  'english-language-p1-language': practice('How does the writer use language in “Rain hammered the empty playground, swallowing every sound”?', 'The violent verb “hammered” makes the weather seem aggressive and relentless, as though the playground is being physically attacked. “Swallowing” personifies the rain as a creature consuming sound, intensifying the emptiness and isolation. Together the verbs transform ordinary weather into a threatening force.', 8, 'Embed short quotations and explore the connotations of individual words.'),
  'english-language-p1-structure': practice('A story opens with a crowded station, narrows to one abandoned suitcase, then ends as the owner runs back. Explain how this structure interests the reader.', 'The broad opening establishes normal movement and anonymity before the focus narrows to the suitcase, making it conspicuous and creating questions about its owner. Delaying the owner’s return sustains tension. The final shift from still object to sudden human movement changes the pace and supplies a partial resolution.', 8, 'Track where the focus moves and explain why each shift occurs at that point.'),
  'english-language-p1-evaluation': practice('A reader says the abandoned suitcase makes the scene immediately threatening. Evaluate this view using the structural outline provided.', 'The suitcase is unsettling because the narrowed focus separates it from the ordinary crowd and encourages the reader to question why it has been left. However, “immediately threatening” may overstate the effect: the opening crowd initially feels routine, and the later return of the owner can resolve rather than confirm danger. The structure creates uncertainty more clearly than definite threat.', 8, 'Make a clear judgement, then support and qualify it with methods and evidence.'),
  'english-language-paper1-writing': practice('Write the opening of a description suggested by the title “After the Storm”.', 'At first, the street seemed to be holding its breath. Water balanced along every railing and gathered in the broken places of the road, turning potholes into small, copper-coloured mirrors. A single leaf loosened itself from the gutter and sailed past the silent houses. Then a door opened. Warm light spread across the pavement, and somewhere behind the clouds a bird began, cautiously, to sing.', 12, 'Control the viewpoint, vary sentence lengths and choose details that create a deliberate atmosphere.'),
  'english-language-p2-q1': practice('Read: “The coach left at six. Although snow covered the hills, the road remained open and every passenger arrived before noon.” Select the four true statements.', 'Four true statements are: the coach left at six; snow covered the hills; the road remained open; every passenger arrived; they arrived before noon. A real Paper 2 Question 1 supplies eight statements, but this mini-task isolates accurate retrieval.', 4, 'Check every selected statement directly against the source.'),
  'english-language-p2-summary': practice('Source A describes a crowded, noisy city market; Source B describes an isolated farm shop where the owner knows every customer. Summarise the differences between the places.', 'Source A appears impersonal and overwhelming because the crowd and noise create constant pressure, whereas Source B feels calm and familiar because few people visit and the owner recognises them. This suggests that commerce in A is fast and anonymous, while in B it is slower and based on personal relationships.', 8, 'Make an inference about each source and support both sides with linked evidence.'),
  'english-language-p2-language': practice('How does the writer present the journey in “The bus crawled uphill, coughing black smoke into the perfect morning”?', 'The verb “crawled” makes the bus seem painfully slow and weak, while “coughing” personifies it as unhealthy and unreliable. The ugly “black smoke” contrasts with the “perfect morning”, presenting the vehicle as an intrusion that spoils both the journey and the landscape.', 8, 'Analyse how the writer’s choices reveal a viewpoint, not just what they describe.'),
  'english-language-p2-comparison': practice('Writer A calls city travel “a daily battle”; Writer B describes cycling to work as “twenty quiet minutes that belong to me”. Compare their viewpoints and methods.', 'Writer A views travel as hostile and exhausting: the metaphor “battle” suggests conflict, repeated effort and other commuters as opponents. In contrast, Writer B values travel as private freedom. “Belong to me” presents the journey as reclaimed personal time, while “quiet” opposes A’s implied chaos. Both use metaphorical language, but one emphasises pressure and the other independence.', 8, 'Compare throughout using both ideas and the methods used to convey them.'),
  'english-language-paper2-writing': practice('Write the opening of a speech arguing that every pupil should learn basic first aid.', 'Imagine knowing exactly what to do while everyone else freezes. Basic first aid is not an optional hobby; it is a practical skill that can protect friends, relatives and strangers. Schools already prepare us for unlikely algebraic problems and historical crises. Surely they can spare a few lessons to prepare us for an emergency that could happen tomorrow. Training would be short, memorable and potentially life-saving.', 12, 'Establish a clear viewpoint, audience and persuasive voice from the first paragraph.'),
  'english-language-spoken': practice('Plan a three-minute presentation answering: “Should phones be restricted during the school day?” Include an opening, three main points, evidence and a response to one likely question.', 'A strong plan opens with a concrete classroom scenario, then argues from concentration, safeguarding and appropriate independence. It uses a statistic or school example cautiously, acknowledges that phones help with travel and emergencies, and proposes storage during lessons rather than a total ban. It ends by restating the balanced recommendation and prepares a concise answer about contacting parents.', 8, 'Plan for listeners: use a clear signposted structure and prepare for questions.'),

  // Pearson Edexcel History 1HI0 topics not already backed by detailed lessons
  'history-edexcel-medieval': practice('Explain one way ideas about the cause of disease affected treatment in medieval England.', 'Many people accepted the Theory of the Four Humours, so physicians tried to restore balance through bleeding or purging. Religious belief also encouraged prayer and pilgrimage. Treatments therefore followed accepted explanations of illness even though they did not address microbes, which were not yet understood.', 4, historyHint),
  'history-edexcel-renaissance': practice('Explain why William Harvey was able to improve understanding of blood circulation in the seventeenth century.', 'Harvey carried out repeated dissections and experiments, including estimating how much blood the heart pumped, which challenged Galen’s claim that blood was constantly made and used up. Renaissance questioning and printed communication helped his evidence circulate, although limited microscopes meant he could not see capillaries.', 8, historyHint),
  'history-edexcel-industrial': practice('Explain why Pasteur’s Germ Theory was an important turning point in medicine.', 'Pasteur used controlled experiments to show that microorganisms caused decay rather than appearing spontaneously. This supplied a scientific explanation for infection and encouraged researchers such as Koch to identify particular bacteria. Its impact was gradual, but it helped transform prevention, surgery and later treatments.', 8, historyHint),
  'history-edexcel-modern-medicine': practice('Explain two reasons why penicillin became widely available during the Second World War.', 'Florey and Chain developed methods to test and produce penicillin after Fleming’s earlier discovery, providing evidence that it could treat infection. Wartime need then brought British and US government funding and industrial cooperation, allowing pharmaceutical companies to mass-produce it for soldiers and later civilians.', 8, historyHint),
  'history-edexcel-elizabeth-government': practice('Explain why Elizabeth I’s Religious Settlement of 1559 was a compromise.', 'The Act of Supremacy restored the monarch as head of the English Church, satisfying Protestants, while the Act of Uniformity established an English prayer book. However, some Catholic-looking features and wording were retained, and Elizabeth demanded outward conformity more than private belief. This aimed to reduce opposition from both sides.', 8, historyHint),
  'history-edexcel-elizabeth-challenges': practice('Explain why the Spanish Armada was defeated in 1588.', 'English ships used speed, manoeuvrability and longer-range guns to disrupt the Spanish formation, while fireships at Calais forced the fleet to scatter. The Spanish plan also depended on joining Parma’s army without a secure deep-water port. Bad weather then worsened losses on the route home, so defeat resulted from tactics, planning weaknesses and conditions.', 8, historyHint),
  'history-edexcel-elizabeth-society': practice('Explain why poverty became a greater concern to Elizabethan governments.', 'Population growth and inflation reduced real wages, while harvest failures and changes in farming increased hardship and movement in search of work. Authorities feared disorder and distinguished between the deserving and idle poor. Local poor relief laws gradually made parishes responsible for collecting rates and supporting those unable to work.', 8, historyHint),
  'history-edexcel-western-front': practice('Explain one way the chain of evacuation improved treatment for wounded soldiers on the Western Front.', 'The chain moved casualties from regimental aid posts through dressing stations and casualty clearing stations to base hospitals. Triage at each stage directed men to suitable treatment, while motor ambulances and ambulance trains moved them more quickly. This increased the chance that serious wounds were operated on before infection or blood loss became fatal.', 4, historyHint),
  'history-edexcel-west-early': practice('Explain two consequences of the Oregon Trail migration for settlement in the West.', 'First, thousands of migrants established farms and communities in Oregon and other western territories, strengthening US claims and expansion. Second, migration increased pressure on Indigenous lands and resources; disease, disrupted hunting and competition contributed to growing tension between settlers and Plains peoples.', 8, historyHint),
  'history-edexcel-west-plains': practice('Explain why the Homestead Act of 1862 encouraged settlement but did not guarantee successful farming.', 'The Act offered 160 acres for a small registration fee if settlers improved and occupied the land, making ownership possible for poorer migrants. However, plots were often too small for the dry Plains, and drought, isolation, lack of timber and expensive equipment caused many claims to fail.', 8, historyHint),
  'history-edexcel-west-later': practice('Explain two consequences of the destruction of the buffalo for Plains peoples.', 'The loss of buffalo removed a central food source and materials used for clothing, shelter and tools, creating hunger and dependence on government rations. It also weakened the ability to resist reservation policy because traditional mobility and economic independence became much harder to sustain.', 8, historyHint),
  'history-edexcel-germany-weimar': practice('Explain why 1923 was a year of crisis for the Weimar Republic.', 'France and Belgium occupied the Ruhr after Germany defaulted on reparations. The government funded passive resistance by printing money, intensifying hyperinflation and destroying savings and wages. Political instability also encouraged extremist challenges including Hitler’s Munich Putsch.', 8, historyHint),
  'history-edexcel-germany-rise': practice('Explain why the Depression increased support for the Nazi Party after 1929.', 'Mass unemployment and business failure weakened confidence in moderate coalition governments, which appeared unable to agree on solutions. Nazi promises of work, national revival and decisive leadership appealed to different groups, while propaganda and Hitler’s speeches converted economic fear into electoral support.', 8, historyHint),
  'history-edexcel-germany-control': practice('Explain how the Nazis created a dictatorship during 1933–34.', 'The Reichstag Fire Decree suspended civil liberties and enabled arrests of opponents. The Enabling Act allowed Hitler to make laws without the Reichstag, after intimidation and Communist exclusion. Trade unions and rival parties were then abolished, and the Night of the Long Knives removed internal rivals before Hitler combined the offices of Chancellor and President.', 8, historyHint),
  'history-edexcel-germany-life': practice('Explain one way Nazi policies affected young people in Germany.', 'The Nazis reshaped education and youth organisations to promote obedience and racial ideology. Textbooks and lessons were altered, while boys in the Hitler Youth prepared for military roles and girls in the League of German Maidens were directed towards motherhood. Participation increasingly replaced independent youth groups and limited alternative influences.', 4, historyHint),
}

export function reviewedPracticeFor(topicId: string): ReviewedPractice | null {
  return REVIEWED_PRACTICE[topicId] ?? confirmedCoursePracticeFor(topicId)
}
