-- Confirmed AQA core courses for the 2027 student cohort.
-- Combined Science: Trilogy is the agreed working assumption and can be
-- replaced by a later migration if entry code 8465 (Synergy) is confirmed.
PRAGMA foreign_keys = ON;

INSERT OR IGNORE INTO subjects (id, name, exam_board, specification_code)
VALUES
  ('subject-mathematics', 'Mathematics', 'AQA', '8300'),
  ('subject-english-language', 'English Language', 'AQA', '8700'),
  ('subject-english-literature', 'English Literature', 'AQA', '8702'),
  ('subject-combined-science', 'Combined Science', 'AQA', '8464');

UPDATE subjects SET exam_board = 'AQA', specification_code = '8300', updated_at = CURRENT_TIMESTAMP
WHERE id = 'subject-mathematics';
UPDATE subjects SET exam_board = 'AQA', specification_code = '8700', updated_at = CURRENT_TIMESTAMP
WHERE id = 'subject-english-language';
UPDATE subjects SET exam_board = 'AQA', specification_code = '8702', updated_at = CURRENT_TIMESTAMP
WHERE id = 'subject-english-literature';
UPDATE subjects SET exam_board = 'AQA', specification_code = '8464', updated_at = CURRENT_TIMESTAMP
WHERE id = 'subject-combined-science';

UPDATE student_subjects
SET tier = 'higher',
    options_json = json_set(options_json, '$.configuration', 'confirmed'),
    updated_at = CURRENT_TIMESTAMP
WHERE subject_id = 'subject-mathematics';

UPDATE student_subjects
SET tier = 'not_applicable',
    options_json = json_set(options_json, '$.configuration', 'confirmed'),
    updated_at = CURRENT_TIMESTAMP
WHERE subject_id = 'subject-english-language';

UPDATE student_subjects
SET tier = 'not_applicable',
    options_json = json_set(
      json_set(
        json_set(
          json_set(json_set(options_json, '$.configuration', 'confirmed'), '$.shakespeare', 'Macbeth'),
          '$.nineteenthCenturyNovel', 'A Christmas Carol'
        ),
        '$.modernText', 'An Inspector Calls'
      ),
      '$.poetryCluster', 'Power and Conflict'
    ),
    updated_at = CURRENT_TIMESTAMP
WHERE subject_id = 'subject-english-literature';

UPDATE student_subjects
SET tier = 'higher',
    options_json = json_set(
      json_set(json_set(options_json, '$.configuration', 'confirmed'), '$.course', 'Trilogy'),
      '$.courseStatus', 'working assumption'
    ),
    updated_at = CURRENT_TIMESTAMP
WHERE subject_id = 'subject-combined-science';

DELETE FROM course_components
WHERE subject_id IN ('subject-mathematics', 'subject-english-language', 'subject-english-literature', 'subject-combined-science');

INSERT INTO course_components
  (id, subject_id, name, component_code, calculator_allowed, duration_minutes, maximum_marks, weighting_percent, tier, sort_order, source_reference)
VALUES
  ('maths-8300-1h', 'subject-mathematics', 'Paper 1: Non-calculator', '8300/1H', 0, 90, 80, 33.3333, 'higher', 1, 'https://www.aqa.org.uk/subjects/mathematics/gcse/mathematics-8300/specification/specification-at-a-glance'),
  ('maths-8300-2h', 'subject-mathematics', 'Paper 2: Calculator', '8300/2H', 1, 90, 80, 33.3333, 'higher', 2, 'https://www.aqa.org.uk/subjects/mathematics/gcse/mathematics-8300/specification/specification-at-a-glance'),
  ('maths-8300-3h', 'subject-mathematics', 'Paper 3: Calculator', '8300/3H', 1, 90, 80, 33.3334, 'higher', 3, 'https://www.aqa.org.uk/subjects/mathematics/gcse/mathematics-8300/specification/specification-at-a-glance'),
  ('english-language-8700-1', 'subject-english-language', 'Paper 1: Explorations in creative reading and writing', '8700/1', 0, 105, 80, 50, 'both', 1, 'https://www.aqa.org.uk/subjects/english/gcse/english-8700/specification/specification-at-a-glance'),
  ('english-language-8700-2', 'subject-english-language', 'Paper 2: Writers viewpoints and perspectives', '8700/2', 0, 105, 80, 50, 'both', 2, 'https://www.aqa.org.uk/subjects/english/gcse/english-8700/specification/specification-at-a-glance'),
  ('english-literature-8702-1', 'subject-english-literature', 'Paper 1: Shakespeare and the 19th-century novel', '8702/1', 0, 105, 64, 40, 'both', 1, 'https://www.aqa.org.uk/subjects/english/gcse/english-literature-8702/specification/specification-at-a-glance'),
  ('english-literature-8702-2', 'subject-english-literature', 'Paper 2: Modern texts and poetry', '8702/2', 0, 135, 96, 60, 'both', 2, 'https://www.aqa.org.uk/subjects/english/gcse/english-literature-8702/specification/specification-at-a-glance'),
  ('science-8464-b1h', 'subject-combined-science', 'Biology Paper 1', '8464/B/1H', 1, 75, 70, 16.6666, 'higher', 1, 'https://www.aqa.org.uk/subjects/science/gcse/science-8464/specification/specification-at-a-glance'),
  ('science-8464-b2h', 'subject-combined-science', 'Biology Paper 2', '8464/B/2H', 1, 75, 70, 16.6666, 'higher', 2, 'https://www.aqa.org.uk/subjects/science/gcse/science-8464/specification/specification-at-a-glance'),
  ('science-8464-c1h', 'subject-combined-science', 'Chemistry Paper 1', '8464/C/1H', 1, 75, 70, 16.6667, 'higher', 3, 'https://www.aqa.org.uk/subjects/science/gcse/science-8464/specification/specification-at-a-glance'),
  ('science-8464-c2h', 'subject-combined-science', 'Chemistry Paper 2', '8464/C/2H', 1, 75, 70, 16.6667, 'higher', 4, 'https://www.aqa.org.uk/subjects/science/gcse/science-8464/specification/specification-at-a-glance'),
  ('science-8464-p1h', 'subject-combined-science', 'Physics Paper 1', '8464/P/1H', 1, 75, 70, 16.6667, 'higher', 5, 'https://www.aqa.org.uk/subjects/science/gcse/science-8464/specification/specification-at-a-glance'),
  ('science-8464-p2h', 'subject-combined-science', 'Physics Paper 2', '8464/P/2H', 1, 75, 70, 16.6667, 'higher', 6, 'https://www.aqa.org.uk/subjects/science/gcse/science-8464/specification/specification-at-a-glance');

-- No prior confirmed maps exist for these subjects. Retain any historical
-- evidence rows but hide obsolete topic rows before installing this map.
UPDATE topics SET active = 0, updated_at = CURRENT_TIMESTAMP
WHERE subject_id IN ('subject-mathematics', 'subject-english-language', 'subject-english-literature', 'subject-combined-science');

INSERT INTO topics
  (id, subject_id, parent_topic_id, component, name, description, exam_board, specification_code, tier, estimated_effort, importance, source_reference, specification_version, applicability)
VALUES
  -- Mathematics: all Higher papers can assess content from any topic area.
  ('maths-number', 'subject-mathematics', NULL, 'All papers', 'Number', 'Structure and calculation; fractions, decimals and percentages; measures and accuracy.', 'AQA', '8300', 'both', 15, 0, 'https://www.aqa.org.uk/subjects/mathematics/gcse/mathematics-8300/specification/subject-content', 'AQA 8300', 'common'),
  ('maths-number-structure', 'subject-mathematics', 'maths-number', 'All papers', 'Integers, place value and ordering', 'Order positive and negative integers, decimals and fractions; use equality and inequality symbols.', 'AQA', '8300', 'both', 2, 1, 'https://www.aqa.org.uk/subjects/mathematics/gcse/mathematics-8300/specification/subject-content', 'AQA 8300', 'common'),
  ('maths-number-calculation', 'subject-mathematics', 'maths-number', 'All papers', 'Calculation and arithmetic', 'Four operations, order of operations, inverse operations and checking calculations.', 'AQA', '8300', 'both', 2, 1, 'https://www.aqa.org.uk/subjects/mathematics/gcse/mathematics-8300/specification/subject-content', 'AQA 8300', 'common'),
  ('maths-number-fdp', 'subject-mathematics', 'maths-number', 'All papers', 'Fractions, decimals and percentages', 'Convert, compare and calculate with fractions, decimals, percentages and recurring decimals.', 'AQA', '8300', 'both', 3, 1, 'https://www.aqa.org.uk/subjects/mathematics/gcse/mathematics-8300/specification/subject-content', 'AQA 8300', 'common'),
  ('maths-number-powers', 'subject-mathematics', 'maths-number', 'All papers', 'Factors, primes, powers and roots', 'Prime factorisation, HCF, LCM, index laws, roots and fractional or negative indices.', 'AQA', '8300', 'both', 3, 1, 'https://www.aqa.org.uk/subjects/mathematics/gcse/mathematics-8300/specification/subject-content', 'AQA 8300', 'common'),
  ('maths-number-standard-surds', 'subject-mathematics', 'maths-number', 'All papers', 'Standard form and surds', 'Calculate with standard form and exact surd values, including rationalising denominators.', 'AQA', '8300', 'higher', 3, 1, 'https://www.aqa.org.uk/subjects/mathematics/gcse/mathematics-8300/specification/subject-content', 'AQA 8300', 'common'),
  ('maths-number-accuracy', 'subject-mathematics', 'maths-number', 'All papers', 'Estimation, rounding and bounds', 'Significant figures, decimal places, error intervals, limits of accuracy and upper and lower bounds.', 'AQA', '8300', 'both', 2, 1, 'https://www.aqa.org.uk/subjects/mathematics/gcse/mathematics-8300/specification/subject-content', 'AQA 8300', 'common'),
  ('maths-algebra', 'subject-mathematics', NULL, 'All papers', 'Algebra', 'Notation, vocabulary and manipulation; graphs; equations and inequalities; sequences.', 'AQA', '8300', 'both', 30, 0, 'https://www.aqa.org.uk/subjects/mathematics/gcse/mathematics-8300/specification/subject-content', 'AQA 8300', 'common'),
  ('maths-algebra-manipulation', 'subject-mathematics', 'maths-algebra', 'All papers', 'Expressions and algebraic manipulation', 'Simplify, expand and factorise expressions; algebraic fractions; identities and proof.', 'AQA', '8300', 'both', 4, 1, 'https://www.aqa.org.uk/subjects/mathematics/gcse/mathematics-8300/specification/subject-content', 'AQA 8300', 'common'),
  ('maths-algebra-equations', 'subject-mathematics', 'maths-algebra', 'All papers', 'Equations and formulae', 'Solve linear and quadratic equations, rearrange formulae and use iterative methods.', 'AQA', '8300', 'both', 4, 1, 'https://www.aqa.org.uk/subjects/mathematics/gcse/mathematics-8300/specification/subject-content', 'AQA 8300', 'common'),
  ('maths-algebra-simultaneous', 'subject-mathematics', 'maths-algebra', 'All papers', 'Simultaneous equations', 'Solve two linear equations and linear-quadratic simultaneous equations algebraically and graphically.', 'AQA', '8300', 'both', 3, 1, 'https://www.aqa.org.uk/subjects/mathematics/gcse/mathematics-8300/specification/subject-content', 'AQA 8300', 'common'),
  ('maths-algebra-inequalities', 'subject-mathematics', 'maths-algebra', 'All papers', 'Inequalities', 'Solve and represent linear and quadratic inequalities, including solution sets.', 'AQA', '8300', 'both', 3, 1, 'https://www.aqa.org.uk/subjects/mathematics/gcse/mathematics-8300/specification/subject-content', 'AQA 8300', 'common'),
  ('maths-algebra-sequences', 'subject-mathematics', 'maths-algebra', 'All papers', 'Sequences', 'Generate and describe arithmetic, quadratic, geometric and Fibonacci-type sequences; find nth terms.', 'AQA', '8300', 'both', 3, 1, 'https://www.aqa.org.uk/subjects/mathematics/gcse/mathematics-8300/specification/subject-content', 'AQA 8300', 'common'),
  ('maths-algebra-graphs', 'subject-mathematics', 'maths-algebra', 'All papers', 'Coordinates and graphs', 'Straight-line, quadratic, cubic, reciprocal, exponential and trigonometric graphs; gradients and areas.', 'AQA', '8300', 'both', 5, 1, 'https://www.aqa.org.uk/subjects/mathematics/gcse/mathematics-8300/specification/subject-content', 'AQA 8300', 'common'),
  ('maths-algebra-functions', 'subject-mathematics', 'maths-algebra', 'All papers', 'Functions and transformations', 'Function notation, inverse and composite functions, and transformations of graphs.', 'AQA', '8300', 'higher', 3, 1, 'https://www.aqa.org.uk/subjects/mathematics/gcse/mathematics-8300/specification/subject-content', 'AQA 8300', 'common'),
  ('maths-ratio', 'subject-mathematics', NULL, 'All papers', 'Ratio, proportion and rates of change', 'Ratio, scale, proportional reasoning, percentages and rates of change.', 'AQA', '8300', 'both', 20, 0, 'https://www.aqa.org.uk/subjects/mathematics/gcse/mathematics-8300/specification/subject-content', 'AQA 8300', 'common'),
  ('maths-ratio-proportion', 'subject-mathematics', 'maths-ratio', 'All papers', 'Ratio and proportional reasoning', 'Simplify and divide ratios, use scale factors and link ratios to fractions and linear functions.', 'AQA', '8300', 'both', 4, 1, 'https://www.aqa.org.uk/subjects/mathematics/gcse/mathematics-8300/specification/subject-content', 'AQA 8300', 'common'),
  ('maths-ratio-direct-inverse', 'subject-mathematics', 'maths-ratio', 'All papers', 'Direct and inverse proportion', 'Recognise, model and solve direct and inverse proportion problems algebraically and graphically.', 'AQA', '8300', 'both', 4, 1, 'https://www.aqa.org.uk/subjects/mathematics/gcse/mathematics-8300/specification/subject-content', 'AQA 8300', 'common'),
  ('maths-ratio-percentages', 'subject-mathematics', 'maths-ratio', 'All papers', 'Percentages and growth', 'Percentage change, reverse percentages, repeated percentage change and compound interest.', 'AQA', '8300', 'both', 4, 1, 'https://www.aqa.org.uk/subjects/mathematics/gcse/mathematics-8300/specification/subject-content', 'AQA 8300', 'common'),
  ('maths-ratio-rates', 'subject-mathematics', 'maths-ratio', 'All papers', 'Rates and compound measures', 'Speed, density, pressure, unit pricing, gradients and interpreting rates of change.', 'AQA', '8300', 'both', 4, 1, 'https://www.aqa.org.uk/subjects/mathematics/gcse/mathematics-8300/specification/subject-content', 'AQA 8300', 'common'),
  ('maths-geometry', 'subject-mathematics', NULL, 'All papers', 'Geometry and measures', 'Properties and constructions; mensuration; transformations and vectors.', 'AQA', '8300', 'both', 20, 0, 'https://www.aqa.org.uk/subjects/mathematics/gcse/mathematics-8300/specification/subject-content', 'AQA 8300', 'common'),
  ('maths-geometry-angles', 'subject-mathematics', 'maths-geometry', 'All papers', 'Angles and polygons', 'Angle facts, parallel lines, polygons and geometrical reasoning.', 'AQA', '8300', 'both', 3, 1, 'https://www.aqa.org.uk/subjects/mathematics/gcse/mathematics-8300/specification/subject-content', 'AQA 8300', 'common'),
  ('maths-geometry-constructions', 'subject-mathematics', 'maths-geometry', 'All papers', 'Constructions, loci and bearings', 'Use rulers and compasses, plans and elevations, loci, bearings and scale drawings.', 'AQA', '8300', 'both', 3, 1, 'https://www.aqa.org.uk/subjects/mathematics/gcse/mathematics-8300/specification/subject-content', 'AQA 8300', 'common'),
  ('maths-geometry-measures', 'subject-mathematics', 'maths-geometry', 'All papers', 'Perimeter, area and volume', 'Calculate measures for 2D and 3D shapes, arcs, sectors and compound shapes.', 'AQA', '8300', 'both', 4, 1, 'https://www.aqa.org.uk/subjects/mathematics/gcse/mathematics-8300/specification/subject-content', 'AQA 8300', 'common'),
  ('maths-geometry-transformations', 'subject-mathematics', 'maths-geometry', 'All papers', 'Transformations and vectors', 'Reflect, rotate, translate and enlarge shapes; use vector notation and vector proofs.', 'AQA', '8300', 'both', 3, 1, 'https://www.aqa.org.uk/subjects/mathematics/gcse/mathematics-8300/specification/subject-content', 'AQA 8300', 'common'),
  ('maths-geometry-similarity', 'subject-mathematics', 'maths-geometry', 'All papers', 'Congruence and similarity', 'Prove congruence and use length, area and volume scale factors.', 'AQA', '8300', 'both', 3, 1, 'https://www.aqa.org.uk/subjects/mathematics/gcse/mathematics-8300/specification/subject-content', 'AQA 8300', 'common'),
  ('maths-geometry-trig', 'subject-mathematics', 'maths-geometry', 'All papers', 'Pythagoras and trigonometry', 'Right-angled trigonometry, exact values, sine and cosine rules, triangle area and 3D problems.', 'AQA', '8300', 'both', 4, 1, 'https://www.aqa.org.uk/subjects/mathematics/gcse/mathematics-8300/specification/subject-content', 'AQA 8300', 'common'),
  ('maths-geometry-circles', 'subject-mathematics', 'maths-geometry', 'All papers', 'Circle geometry', 'Circle properties, equations of circles, tangents and circle theorems.', 'AQA', '8300', 'higher', 3, 1, 'https://www.aqa.org.uk/subjects/mathematics/gcse/mathematics-8300/specification/subject-content', 'AQA 8300', 'common'),
  ('maths-probability', 'subject-mathematics', NULL, 'All papers', 'Probability', 'Probability experiments, combined events, conditional probability and diagrams.', 'AQA', '8300', 'both', 8, 0, 'https://www.aqa.org.uk/subjects/mathematics/gcse/mathematics-8300/specification/subject-content', 'AQA 8300', 'common'),
  ('maths-probability-basics', 'subject-mathematics', 'maths-probability', 'All papers', 'Probability foundations', 'The probability scale, theoretical and experimental probability, expected outcomes and exhaustive events.', 'AQA', '8300', 'both', 3, 1, 'https://www.aqa.org.uk/subjects/mathematics/gcse/mathematics-8300/specification/subject-content', 'AQA 8300', 'common'),
  ('maths-probability-combined', 'subject-mathematics', 'maths-probability', 'All papers', 'Combined and conditional probability', 'Use sample spaces, frequency trees, tree diagrams, Venn diagrams and conditional probability.', 'AQA', '8300', 'both', 4, 1, 'https://www.aqa.org.uk/subjects/mathematics/gcse/mathematics-8300/specification/subject-content', 'AQA 8300', 'common'),
  ('maths-statistics', 'subject-mathematics', NULL, 'All papers', 'Statistics', 'Sampling, representing data and interpreting distributions.', 'AQA', '8300', 'both', 7, 0, 'https://www.aqa.org.uk/subjects/mathematics/gcse/mathematics-8300/specification/subject-content', 'AQA 8300', 'common'),
  ('maths-statistics-sampling', 'subject-mathematics', 'maths-statistics', 'All papers', 'Populations and sampling', 'Identify populations, use samples and understand limitations and bias.', 'AQA', '8300', 'both', 2, 1, 'https://www.aqa.org.uk/subjects/mathematics/gcse/mathematics-8300/specification/subject-content', 'AQA 8300', 'common'),
  ('maths-statistics-represent', 'subject-mathematics', 'maths-statistics', 'All papers', 'Representing data', 'Tables, charts, time series, scatter graphs, histograms, cumulative frequency and box plots.', 'AQA', '8300', 'both', 3, 1, 'https://www.aqa.org.uk/subjects/mathematics/gcse/mathematics-8300/specification/subject-content', 'AQA 8300', 'common'),
  ('maths-statistics-interpret', 'subject-mathematics', 'maths-statistics', 'All papers', 'Averages, spread and interpretation', 'Mean, median, mode, range, quartiles, interquartile range, correlation and comparing distributions.', 'AQA', '8300', 'both', 3, 1, 'https://www.aqa.org.uk/subjects/mathematics/gcse/mathematics-8300/specification/subject-content', 'AQA 8300', 'common'),

  -- English Language: examination texts are unseen, so topics are the assessed skills.
  ('english-language-paper1-reading', 'subject-english-language', NULL, 'Paper 1 Section A', 'Creative reading', 'Retrieve information and analyse language, structure and effects in an unseen fiction extract.', 'AQA', '8700', 'both', 10, 0, 'https://www.aqa.org.uk/subjects/english/gcse/english-8700/specification/specification-at-a-glance', 'AQA 8700', 'common'),
  ('english-language-p1-q1', 'subject-english-language', 'english-language-paper1-reading', 'Paper 1 Section A', 'Selecting explicit information', 'Select four relevant details from a specified part of the source.', 'AQA', '8700', 'both', 1, 1, 'https://www.aqa.org.uk/subjects/english/gcse/english-8700/specification/specification-at-a-glance', 'AQA 8700', 'common'),
  ('english-language-p1-language', 'subject-english-language', 'english-language-paper1-reading', 'Paper 1 Section A', 'Analysing language', 'Explain how vocabulary, imagery and sentence choices create meanings and effects.', 'AQA', '8700', 'both', 3, 1, 'https://www.aqa.org.uk/subjects/english/gcse/english-8700/specification/specification-at-a-glance', 'AQA 8700', 'common'),
  ('english-language-p1-structure', 'subject-english-language', 'english-language-paper1-reading', 'Paper 1 Section A', 'Analysing structure', 'Explain how focus, sequence, contrast, pace and shifts interest the reader.', 'AQA', '8700', 'both', 3, 1, 'https://www.aqa.org.uk/subjects/english/gcse/english-8700/specification/specification-at-a-glance', 'AQA 8700', 'common'),
  ('english-language-p1-evaluation', 'subject-english-language', 'english-language-paper1-reading', 'Paper 1 Section A', 'Evaluating a text', 'Judge a statement about the text using precise evidence and analysis of methods.', 'AQA', '8700', 'both', 3, 1, 'https://www.aqa.org.uk/subjects/english/gcse/english-8700/specification/specification-at-a-glance', 'AQA 8700', 'common'),
  ('english-language-paper1-writing', 'subject-english-language', NULL, 'Paper 1 Section B', 'Creative writing', 'Write an effective description or narrative with deliberate organisation and accurate technical control.', 'AQA', '8700', 'both', 8, 1, 'https://www.aqa.org.uk/subjects/english/gcse/english-8700/specification/specification-at-a-glance', 'AQA 8700', 'common'),
  ('english-language-paper2-reading', 'subject-english-language', NULL, 'Paper 2 Section A', 'Writers viewpoints and perspectives', 'Read, synthesise, analyse and compare one non-fiction and one literary non-fiction text.', 'AQA', '8700', 'both', 10, 0, 'https://www.aqa.org.uk/subjects/english/gcse/english-8700/specification/specification-at-a-glance', 'AQA 8700', 'common'),
  ('english-language-p2-q1', 'subject-english-language', 'english-language-paper2-reading', 'Paper 2 Section A', 'Identifying true statements', 'Select four true statements from a specified part of a source.', 'AQA', '8700', 'both', 1, 1, 'https://www.aqa.org.uk/subjects/english/gcse/english-8700/specification/specification-at-a-glance', 'AQA 8700', 'common'),
  ('english-language-p2-summary', 'subject-english-language', 'english-language-paper2-reading', 'Paper 2 Section A', 'Synthesising differences', 'Infer and summarise differences or similarities across two sources.', 'AQA', '8700', 'both', 2, 1, 'https://www.aqa.org.uk/subjects/english/gcse/english-8700/specification/specification-at-a-glance', 'AQA 8700', 'common'),
  ('english-language-p2-language', 'subject-english-language', 'english-language-paper2-reading', 'Paper 2 Section A', 'Analysing non-fiction language', 'Explain how a writer uses language to present a viewpoint or experience.', 'AQA', '8700', 'both', 3, 1, 'https://www.aqa.org.uk/subjects/english/gcse/english-8700/specification/specification-at-a-glance', 'AQA 8700', 'common'),
  ('english-language-p2-comparison', 'subject-english-language', 'english-language-paper2-reading', 'Paper 2 Section A', 'Comparing viewpoints and methods', 'Compare perspectives and how the writers convey them across both sources.', 'AQA', '8700', 'both', 4, 1, 'https://www.aqa.org.uk/subjects/english/gcse/english-8700/specification/specification-at-a-glance', 'AQA 8700', 'common'),
  ('english-language-paper2-writing', 'subject-english-language', NULL, 'Paper 2 Section B', 'Writing a viewpoint', 'Write a coherent argument or viewpoint for a specified audience, purpose and form.', 'AQA', '8700', 'both', 8, 1, 'https://www.aqa.org.uk/subjects/english/gcse/english-8700/specification/specification-at-a-glance', 'AQA 8700', 'common'),
  ('english-language-spoken', 'subject-english-language', NULL, 'Spoken Language endorsement', 'Spoken Language', 'Present information and ideas, respond to questions and use spoken Standard English.', 'AQA', '8700', 'both', 3, 1, 'https://www.aqa.org.uk/subjects/english/gcse/english-8700/specification/specification-at-a-glance', 'AQA 8700', 'common'),

  -- English Literature: the three set texts and Power and Conflict are confirmed.
  ('english-lit-macbeth', 'subject-english-literature', NULL, 'Paper 1 Section A', 'Macbeth', 'Shakespeare play: whole-text knowledge, extract analysis, themes, characters, methods and context.', 'AQA', '8702', 'both', 12, 0, 'https://www.aqa.org.uk/subjects/english/gcse/english-literature-8702/specification/subject-content/shakespeare-and-the-19th-century-novel', 'AQA 8702', 'common'),
  ('english-lit-macbeth-plot', 'subject-english-literature', 'english-lit-macbeth', 'Paper 1 Section A', 'Macbeth: plot and structure', 'Track the tragedy from the witches prophecy through regicide, tyranny and restoration.', 'AQA', '8702', 'both', 3, 1, 'https://www.aqa.org.uk/subjects/english/gcse/english-literature-8702/specification/subject-content/shakespeare-and-the-19th-century-novel', 'AQA 8702', 'common'),
  ('english-lit-macbeth-characters', 'subject-english-literature', 'english-lit-macbeth', 'Paper 1 Section A', 'Macbeth: characters', 'Macbeth, Lady Macbeth, Banquo, Macduff, Duncan, Malcolm and the witches.', 'AQA', '8702', 'both', 3, 1, 'https://www.aqa.org.uk/subjects/english/gcse/english-literature-8702/specification/subject-content/shakespeare-and-the-19th-century-novel', 'AQA 8702', 'common'),
  ('english-lit-macbeth-themes', 'subject-english-literature', 'english-lit-macbeth', 'Paper 1 Section A', 'Macbeth: themes and context', 'Ambition, power, guilt, the supernatural, kingship, violence, gender and Jacobean context.', 'AQA', '8702', 'both', 3, 1, 'https://www.aqa.org.uk/subjects/english/gcse/english-literature-8702/specification/subject-content/shakespeare-and-the-19th-century-novel', 'AQA 8702', 'common'),
  ('english-lit-macbeth-methods', 'subject-english-literature', 'english-lit-macbeth', 'Paper 1 Section A', 'Macbeth: language, form and structure', 'Analyse imagery, motifs, soliloquies, dramatic irony, contrast and tragic form using precise references.', 'AQA', '8702', 'both', 3, 1, 'https://www.aqa.org.uk/subjects/english/gcse/english-literature-8702/specification/subject-content/shakespeare-and-the-19th-century-novel', 'AQA 8702', 'common'),
  ('english-lit-carol', 'subject-english-literature', NULL, 'Paper 1 Section B', 'A Christmas Carol', 'Dickens novella: whole-text knowledge, extract analysis, themes, characters, methods and context.', 'AQA', '8702', 'both', 12, 0, 'https://www.aqa.org.uk/subjects/english/gcse/english-literature-8702/specification/subject-content/shakespeare-and-the-19th-century-novel', 'AQA 8702', 'common'),
  ('english-lit-carol-plot', 'subject-english-literature', 'english-lit-carol', 'Paper 1 Section B', 'A Christmas Carol: plot and structure', 'Track Scrooge through the five staves and explain the purpose of his transformation.', 'AQA', '8702', 'both', 3, 1, 'https://www.aqa.org.uk/subjects/english/gcse/english-literature-8702/specification/subject-content/shakespeare-and-the-19th-century-novel', 'AQA 8702', 'common'),
  ('english-lit-carol-characters', 'subject-english-literature', 'english-lit-carol', 'Paper 1 Section B', 'A Christmas Carol: characters', 'Scrooge, Marley, the three Ghosts, the Cratchits, Fred, Fezziwig and Belle.', 'AQA', '8702', 'both', 3, 1, 'https://www.aqa.org.uk/subjects/english/gcse/english-literature-8702/specification/subject-content/shakespeare-and-the-19th-century-novel', 'AQA 8702', 'common'),
  ('english-lit-carol-themes', 'subject-english-literature', 'english-lit-carol', 'Paper 1 Section B', 'A Christmas Carol: themes and context', 'Redemption, social responsibility, poverty, family, Christmas, education and Victorian context.', 'AQA', '8702', 'both', 3, 1, 'https://www.aqa.org.uk/subjects/english/gcse/english-literature-8702/specification/subject-content/shakespeare-and-the-19th-century-novel', 'AQA 8702', 'common'),
  ('english-lit-carol-methods', 'subject-english-literature', 'english-lit-carol', 'Paper 1 Section B', 'A Christmas Carol: language, form and structure', 'Analyse symbolism, contrasts, narrative voice, setting, supernatural elements and the novella form.', 'AQA', '8702', 'both', 3, 1, 'https://www.aqa.org.uk/subjects/english/gcse/english-literature-8702/specification/subject-content/shakespeare-and-the-19th-century-novel', 'AQA 8702', 'common'),
  ('english-lit-inspector', 'subject-english-literature', NULL, 'Paper 2 Section A', 'An Inspector Calls', 'Priestley play: whole-text knowledge, themes, characters, dramatic methods and context.', 'AQA', '8702', 'both', 12, 0, 'https://www.aqa.org.uk/subjects/english/gcse/english-literature-8702/specification/subject-content/modern-texts-and-poetry', 'AQA 8702', 'common'),
  ('english-lit-inspector-plot', 'subject-english-literature', 'english-lit-inspector', 'Paper 2 Section A', 'An Inspector Calls: plot and structure', 'Track the investigation, revelations, ending and use of time and dramatic tension.', 'AQA', '8702', 'both', 3, 1, 'https://www.aqa.org.uk/subjects/english/gcse/english-literature-8702/specification/subject-content/modern-texts-and-poetry', 'AQA 8702', 'common'),
  ('english-lit-inspector-characters', 'subject-english-literature', 'english-lit-inspector', 'Paper 2 Section A', 'An Inspector Calls: characters', 'Inspector Goole, Arthur and Sybil Birling, Sheila, Eric, Gerald and Eva Smith.', 'AQA', '8702', 'both', 3, 1, 'https://www.aqa.org.uk/subjects/english/gcse/english-literature-8702/specification/subject-content/modern-texts-and-poetry', 'AQA 8702', 'common'),
  ('english-lit-inspector-themes', 'subject-english-literature', 'english-lit-inspector', 'Paper 2 Section A', 'An Inspector Calls: themes and context', 'Responsibility, class, gender, age, power, capitalism, socialism and 1912 versus 1945.', 'AQA', '8702', 'both', 3, 1, 'https://www.aqa.org.uk/subjects/english/gcse/english-literature-8702/specification/subject-content/modern-texts-and-poetry', 'AQA 8702', 'common'),
  ('english-lit-inspector-methods', 'subject-english-literature', 'english-lit-inspector', 'Paper 2 Section A', 'An Inspector Calls: dramatic methods', 'Analyse stage directions, dramatic irony, lighting, entrances and exits, contrast and cyclical structure.', 'AQA', '8702', 'both', 3, 1, 'https://www.aqa.org.uk/subjects/english/gcse/english-literature-8702/specification/subject-content/modern-texts-and-poetry', 'AQA 8702', 'common'),
  ('english-lit-power-conflict', 'subject-english-literature', NULL, 'Paper 2 Section B', 'Power and Conflict poetry', 'Study all 15 anthology poems and compare ideas, perspectives, language, form, structure and context.', 'AQA', '8702', 'both', 30, 0, 'https://www.aqa.org.uk/subjects/english/gcse/english-literature-8702/specification/subject-content/modern-texts-and-poetry', 'AQA 8702', 'common'),
  ('english-lit-poem-ozymandias', 'subject-english-literature', 'english-lit-power-conflict', 'Paper 2 Section B', 'Ozymandias', 'Shelley: power, pride, decline, nature and the transience of human authority.', 'AQA', '8702', 'both', 2, 1, 'https://www.aqa.org.uk/subjects/english/gcse/english-literature-8702/specification/subject-content/modern-texts-and-poetry', 'AQA 8702', 'common'),
  ('english-lit-poem-london', 'subject-english-literature', 'english-lit-power-conflict', 'Paper 2 Section B', 'London', 'Blake: institutional power, oppression, suffering and restriction.', 'AQA', '8702', 'both', 2, 1, 'https://www.aqa.org.uk/subjects/english/gcse/english-literature-8702/specification/subject-content/modern-texts-and-poetry', 'AQA 8702', 'common'),
  ('english-lit-poem-prelude', 'subject-english-literature', 'english-lit-power-conflict', 'Paper 2 Section B', 'Extract from The Prelude', 'Wordsworth: overwhelming natural power, fear, awe and changed identity.', 'AQA', '8702', 'both', 2, 1, 'https://www.aqa.org.uk/subjects/english/gcse/english-literature-8702/specification/subject-content/modern-texts-and-poetry', 'AQA 8702', 'common'),
  ('english-lit-poem-duchess', 'subject-english-literature', 'english-lit-power-conflict', 'Paper 2 Section B', 'My Last Duchess', 'Browning: control, jealousy, patriarchal power and dramatic monologue.', 'AQA', '8702', 'both', 2, 1, 'https://www.aqa.org.uk/subjects/english/gcse/english-literature-8702/specification/subject-content/modern-texts-and-poetry', 'AQA 8702', 'common'),
  ('english-lit-poem-charge', 'subject-english-literature', 'english-lit-power-conflict', 'Paper 2 Section B', 'The Charge of the Light Brigade', 'Tennyson: conflict, duty, courage, sacrifice and military command.', 'AQA', '8702', 'both', 2, 1, 'https://www.aqa.org.uk/subjects/english/gcse/english-literature-8702/specification/subject-content/modern-texts-and-poetry', 'AQA 8702', 'common'),
  ('english-lit-poem-exposure', 'subject-english-literature', 'english-lit-power-conflict', 'Paper 2 Section B', 'Exposure', 'Owen: futility, suffering, waiting and the hostility of nature in war.', 'AQA', '8702', 'both', 2, 1, 'https://www.aqa.org.uk/subjects/english/gcse/english-literature-8702/specification/subject-content/modern-texts-and-poetry', 'AQA 8702', 'common'),
  ('english-lit-poem-storm', 'subject-english-literature', 'english-lit-power-conflict', 'Paper 2 Section B', 'Storm on the Island', 'Heaney: natural power, community, fear and an invisible threat.', 'AQA', '8702', 'both', 2, 1, 'https://www.aqa.org.uk/subjects/english/gcse/english-literature-8702/specification/subject-content/modern-texts-and-poetry', 'AQA 8702', 'common'),
  ('english-lit-poem-bayonet', 'subject-english-literature', 'english-lit-power-conflict', 'Paper 2 Section B', 'Bayonet Charge', 'Hughes: terror, instinct, patriotism and the individual experience of battle.', 'AQA', '8702', 'both', 2, 1, 'https://www.aqa.org.uk/subjects/english/gcse/english-literature-8702/specification/subject-content/modern-texts-and-poetry', 'AQA 8702', 'common'),
  ('english-lit-poem-remains', 'subject-english-literature', 'english-lit-power-conflict', 'Paper 2 Section B', 'Remains', 'Armitage: guilt, trauma, memory and the lasting effects of conflict.', 'AQA', '8702', 'both', 2, 1, 'https://www.aqa.org.uk/subjects/english/gcse/english-literature-8702/specification/subject-content/modern-texts-and-poetry', 'AQA 8702', 'common'),
  ('english-lit-poem-poppies', 'subject-english-literature', 'english-lit-power-conflict', 'Paper 2 Section B', 'Poppies', 'Weir: loss, memory, family and a parents experience of conflict.', 'AQA', '8702', 'both', 2, 1, 'https://www.aqa.org.uk/subjects/english/gcse/english-literature-8702/specification/subject-content/modern-texts-and-poetry', 'AQA 8702', 'common'),
  ('english-lit-poem-war-photographer', 'subject-english-literature', 'english-lit-power-conflict', 'Paper 2 Section B', 'War Photographer', 'Duffy: witnessing suffering, memory, moral responsibility and public indifference.', 'AQA', '8702', 'both', 2, 1, 'https://www.aqa.org.uk/subjects/english/gcse/english-literature-8702/specification/subject-content/modern-texts-and-poetry', 'AQA 8702', 'common'),
  ('english-lit-poem-tissue', 'subject-english-literature', 'english-lit-power-conflict', 'Paper 2 Section B', 'Tissue', 'Dharker: fragile human power, paper, identity, creation and impermanence.', 'AQA', '8702', 'both', 2, 1, 'https://www.aqa.org.uk/subjects/english/gcse/english-literature-8702/specification/subject-content/modern-texts-and-poetry', 'AQA 8702', 'common'),
  ('english-lit-poem-emigree', 'subject-english-literature', 'english-lit-power-conflict', 'Paper 2 Section B', 'The Emigree', 'Rumens: memory, displacement, identity, conflict and an idealised homeland.', 'AQA', '8702', 'both', 2, 1, 'https://www.aqa.org.uk/subjects/english/gcse/english-literature-8702/specification/subject-content/modern-texts-and-poetry', 'AQA 8702', 'common'),
  ('english-lit-poem-history', 'subject-english-literature', 'english-lit-power-conflict', 'Paper 2 Section B', 'Checking Out Me History', 'Agard: identity, education, resistance and the power to control history.', 'AQA', '8702', 'both', 2, 1, 'https://www.aqa.org.uk/subjects/english/gcse/english-literature-8702/specification/subject-content/modern-texts-and-poetry', 'AQA 8702', 'common'),
  ('english-lit-poem-kamikaze', 'subject-english-literature', 'english-lit-power-conflict', 'Paper 2 Section B', 'Kamikaze', 'Garland: duty, identity, family, nature, shame and the consequences of conflict.', 'AQA', '8702', 'both', 2, 1, 'https://www.aqa.org.uk/subjects/english/gcse/english-literature-8702/specification/subject-content/modern-texts-and-poetry', 'AQA 8702', 'common'),
  ('english-lit-unseen', 'subject-english-literature', NULL, 'Paper 2 Section C', 'Unseen poetry', 'Analyse one unseen poem and compare methods in a second unseen poem.', 'AQA', '8702', 'both', 8, 1, 'https://www.aqa.org.uk/subjects/english/gcse/english-literature-8702/specification/subject-content/modern-texts-and-poetry', 'AQA 8702', 'common'),

  -- Combined Science: Trilogy. Each official main topic is a schedulable unit;
  -- descriptions enumerate the examinable strands, including Higher content.
  ('science-b-cell', 'subject-combined-science', NULL, 'Biology Paper 1', 'Cell biology', 'Cell structure; microscopy; cell differentiation; chromosomes and mitosis; stem cells; diffusion, osmosis and active transport.', 'AQA', '8464', 'both', 7, 1, 'https://www.aqa.org.uk/subjects/science/gcse/science-8464/specification/biology-subject-content', 'AQA 8464 Trilogy', 'common'),
  ('science-b-organisation', 'subject-combined-science', NULL, 'Biology Paper 1', 'Organisation', 'Cells, tissues and organs; digestion and enzymes; heart, blood and vessels; health and disease; plant tissues and transport.', 'AQA', '8464', 'both', 8, 1, 'https://www.aqa.org.uk/subjects/science/gcse/science-8464/specification/biology-subject-content', 'AQA 8464 Trilogy', 'common'),
  ('science-b-infection', 'subject-combined-science', NULL, 'Biology Paper 1', 'Infection and response', 'Pathogens and disease; human defences; vaccination; antibiotics and drug development; monoclonal antibodies; plant disease.', 'AQA', '8464', 'both', 7, 1, 'https://www.aqa.org.uk/subjects/science/gcse/science-8464/specification/biology-subject-content', 'AQA 8464 Trilogy', 'common'),
  ('science-b-bioenergetics', 'subject-combined-science', NULL, 'Biology Paper 1', 'Bioenergetics', 'Photosynthesis and limiting factors; aerobic and anaerobic respiration; response to exercise; metabolism.', 'AQA', '8464', 'both', 5, 1, 'https://www.aqa.org.uk/subjects/science/gcse/science-8464/specification/biology-subject-content', 'AQA 8464 Trilogy', 'common'),
  ('science-b-homeostasis', 'subject-combined-science', NULL, 'Biology Paper 2', 'Homeostasis and response', 'Homeostasis; nervous and hormonal control; reflexes; the brain and eye; temperature and blood glucose; kidneys; reproduction and hormones.', 'AQA', '8464', 'both', 9, 1, 'https://www.aqa.org.uk/subjects/science/gcse/science-8464/specification/biology-subject-content', 'AQA 8464 Trilogy', 'common'),
  ('science-b-inheritance', 'subject-combined-science', NULL, 'Biology Paper 2', 'Inheritance, variation and evolution', 'Sexual and asexual reproduction; DNA and genes; inheritance; variation; evolution; selective breeding and genetic engineering; classification.', 'AQA', '8464', 'both', 9, 1, 'https://www.aqa.org.uk/subjects/science/gcse/science-8464/specification/biology-subject-content', 'AQA 8464 Trilogy', 'common'),
  ('science-b-ecology', 'subject-combined-science', NULL, 'Biology Paper 2', 'Ecology', 'Communities and ecosystems; abiotic and biotic factors; adaptations; organisation; cycles and decomposition; biodiversity and food security.', 'AQA', '8464', 'both', 8, 1, 'https://www.aqa.org.uk/subjects/science/gcse/science-8464/specification/biology-subject-content', 'AQA 8464 Trilogy', 'common'),
  ('science-c-atomic', 'subject-combined-science', NULL, 'Chemistry Paper 1', 'Atomic structure and the periodic table', 'Atoms, elements, mixtures and equations; atomic models and electronic structure; periodic table development; Groups 0, 1 and 7; transition metals.', 'AQA', '8464', 'both', 7, 1, 'https://www.aqa.org.uk/subjects/science/gcse/science-8464/specification/chemistry-subject-content', 'AQA 8464 Trilogy', 'common'),
  ('science-c-bonding', 'subject-combined-science', NULL, 'Chemistry Paper 1', 'Bonding, structure and properties of matter', 'Ionic, covalent and metallic bonding; states of matter; simple molecules, polymers and giant structures; nanoparticles.', 'AQA', '8464', 'both', 8, 1, 'https://www.aqa.org.uk/subjects/science/gcse/science-8464/specification/chemistry-subject-content', 'AQA 8464 Trilogy', 'common'),
  ('science-c-quantitative', 'subject-combined-science', NULL, 'Chemistry Paper 1', 'Quantitative chemistry', 'Relative masses and moles; equations; reacting masses; concentration; percentage yield; atom economy; gas volumes.', 'AQA', '8464', 'both', 9, 1, 'https://www.aqa.org.uk/subjects/science/gcse/science-8464/specification/chemistry-subject-content', 'AQA 8464 Trilogy', 'common'),
  ('science-c-changes', 'subject-combined-science', NULL, 'Chemistry Paper 1', 'Chemical changes', 'Reactivity; extraction and oxidation; acids, salts and pH; electrolysis of molten and aqueous substances.', 'AQA', '8464', 'both', 8, 1, 'https://www.aqa.org.uk/subjects/science/gcse/science-8464/specification/chemistry-subject-content', 'AQA 8464 Trilogy', 'common'),
  ('science-c-energy', 'subject-combined-science', NULL, 'Chemistry Paper 1', 'Energy changes', 'Exothermic and endothermic reactions; reaction profiles; bond energies; cells and fuel cells.', 'AQA', '8464', 'both', 5, 1, 'https://www.aqa.org.uk/subjects/science/gcse/science-8464/specification/chemistry-subject-content', 'AQA 8464 Trilogy', 'common'),
  ('science-c-rates', 'subject-combined-science', NULL, 'Chemistry Paper 2', 'Rate and extent of chemical change', 'Measuring rate; collision theory; effects of temperature, concentration, pressure, surface area and catalysts; reversible reactions and equilibrium.', 'AQA', '8464', 'both', 7, 1, 'https://www.aqa.org.uk/subjects/science/gcse/science-8464/specification/chemistry-subject-content', 'AQA 8464 Trilogy', 'common'),
  ('science-c-organic', 'subject-combined-science', NULL, 'Chemistry Paper 2', 'Organic chemistry', 'Crude oil and hydrocarbons; fractional distillation; properties of alkanes; cracking; alkenes and polymers.', 'AQA', '8464', 'both', 6, 1, 'https://www.aqa.org.uk/subjects/science/gcse/science-8464/specification/chemistry-subject-content', 'AQA 8464 Trilogy', 'common'),
  ('science-c-analysis', 'subject-combined-science', NULL, 'Chemistry Paper 2', 'Chemical analysis', 'Pure substances and formulations; chromatography; gas tests; flame tests and identifying ions.', 'AQA', '8464', 'both', 6, 1, 'https://www.aqa.org.uk/subjects/science/gcse/science-8464/specification/chemistry-subject-content', 'AQA 8464 Trilogy', 'common'),
  ('science-c-atmosphere', 'subject-combined-science', NULL, 'Chemistry Paper 2', 'Chemistry of the atmosphere', 'Evolution of the atmosphere; greenhouse gases and climate change; carbon footprints; atmospheric pollutants.', 'AQA', '8464', 'both', 5, 1, 'https://www.aqa.org.uk/subjects/science/gcse/science-8464/specification/chemistry-subject-content', 'AQA 8464 Trilogy', 'common'),
  ('science-c-resources', 'subject-combined-science', NULL, 'Chemistry Paper 2', 'Using resources', 'Finite and renewable resources; potable water and waste water; life-cycle assessment and recycling; corrosion, alloys and materials; Haber process and fertilisers.', 'AQA', '8464', 'both', 7, 1, 'https://www.aqa.org.uk/subjects/science/gcse/science-8464/specification/chemistry-subject-content', 'AQA 8464 Trilogy', 'common'),
  ('science-p-energy', 'subject-combined-science', NULL, 'Physics Paper 1', 'Energy', 'Energy stores and transfers; kinetic, elastic and gravitational energy; power; efficiency; heating; national and global energy resources.', 'AQA', '8464', 'both', 7, 1, 'https://www.aqa.org.uk/subjects/science/gcse/science-8464/specification/physics-subject-content', 'AQA 8464 Trilogy', 'common'),
  ('science-p-electricity', 'subject-combined-science', NULL, 'Physics Paper 1', 'Electricity', 'Current, potential difference and resistance; series and parallel circuits; domestic electricity; power and energy transfers; the National Grid; static electricity.', 'AQA', '8464', 'both', 9, 1, 'https://www.aqa.org.uk/subjects/science/gcse/science-8464/specification/physics-subject-content', 'AQA 8464 Trilogy', 'common'),
  ('science-p-particles', 'subject-combined-science', NULL, 'Physics Paper 1', 'Particle model of matter', 'Density; changes of state; internal energy; specific heat capacity and latent heat; gas pressure and temperature.', 'AQA', '8464', 'both', 7, 1, 'https://www.aqa.org.uk/subjects/science/gcse/science-8464/specification/physics-subject-content', 'AQA 8464 Trilogy', 'common'),
  ('science-p-atomic', 'subject-combined-science', NULL, 'Physics Paper 1', 'Atomic structure', 'Atomic models; isotopes and nuclear radiation; half-life and contamination; uses and hazards of radiation.', 'AQA', '8464', 'both', 7, 1, 'https://www.aqa.org.uk/subjects/science/gcse/science-8464/specification/physics-subject-content', 'AQA 8464 Trilogy', 'common'),
  ('science-p-forces', 'subject-combined-science', NULL, 'Physics Paper 2', 'Forces', 'Scalars and vectors; contact and non-contact forces; elasticity; moments and pressure; motion graphs; Newton laws; stopping distance and momentum.', 'AQA', '8464', 'both', 11, 1, 'https://www.aqa.org.uk/subjects/science/gcse/science-8464/specification/physics-subject-content', 'AQA 8464 Trilogy', 'common'),
  ('science-p-waves', 'subject-combined-science', NULL, 'Physics Paper 2', 'Waves', 'Wave properties and equations; reflection and refraction; sound and ultrasound; electromagnetic spectrum; lenses, colour and black-body radiation.', 'AQA', '8464', 'both', 9, 1, 'https://www.aqa.org.uk/subjects/science/gcse/science-8464/specification/physics-subject-content', 'AQA 8464 Trilogy', 'common'),
  ('science-p-magnetism', 'subject-combined-science', NULL, 'Physics Paper 2', 'Magnetism and electromagnetism', 'Magnets and magnetic fields; electromagnets; motor effect; electric motors; generators, transformers and microphones.', 'AQA', '8464', 'both', 7, 1, 'https://www.aqa.org.uk/subjects/science/gcse/science-8464/specification/physics-subject-content', 'AQA 8464 Trilogy', 'common');

INSERT INTO subject_revision_guides
  (subject_id, exam_summary, assessment_objectives_json, exam_tips_json, specification_url, assessment_resources_url, provisional, verified_at)
VALUES
  ('subject-mathematics', 'AQA GCSE Mathematics 8300 Higher: three 1 hour 30 minute papers of 80 marks each. Paper 1 is non-calculator; Papers 2 and 3 allow a calculator. Content from any topic may appear on any paper.', '["AO1: use and apply standard techniques","AO2: reason, interpret and communicate mathematically","AO3: solve problems within mathematics and other contexts"]', '["Show complete working even when using a calculator","Check units, rounding and whether an answer is reasonable","Practise unfamiliar multi-step problems as well as routine methods","Learn the required formulae and know how to use the supplied formulae sheet"]', 'https://www.aqa.org.uk/subjects/mathematics/gcse/mathematics-8300/specification', 'https://www.aqa.org.uk/subjects/mathematics/gcse/mathematics-8300/assessment-resources', 0, '2026-09-26'),
  ('subject-english-language', 'AQA GCSE English Language 8700: Paper 1 Explorations in creative reading and writing and Paper 2 Writers viewpoints and perspectives, each 1 hour 45 minutes, 80 marks and 50%. Spoken Language is separately endorsed.', '["AO1: identify and interpret information and ideas","AO2: explain and analyse language and structure","AO3: compare writers ideas and perspectives","AO4: evaluate texts critically","AO5: communicate clearly and imaginatively for audience and purpose","AO6: use accurate vocabulary, sentences, spelling and punctuation","AO7-AO9: spoken presentation, response and Standard English"]', '["Use short, precise evidence and analyse its effect","Answer the exact focus and source lines in each reading question","Plan writing for audience, purpose and form","Reserve time to check paragraphing, sentences, spelling and punctuation"]', 'https://www.aqa.org.uk/subjects/english/gcse/english-8700/specification', 'https://www.aqa.org.uk/subjects/english/gcse/english-8700/assessment-resources', 0, '2026-09-26'),
  ('subject-english-literature', 'AQA GCSE English Literature 8702: Paper 1 Macbeth and A Christmas Carol (1 hour 45 minutes, 64 marks, 40%); Paper 2 An Inspector Calls, Power and Conflict anthology and unseen poetry (2 hours 15 minutes, 96 marks, 60%). Exams are closed book.', '["AO1: respond critically and use textual references","AO2: analyse language, form and structure","AO3: show understanding of texts and contexts","AO4: use accurate vocabulary, sentences, spelling and punctuation"]', '["Learn flexible short quotations for each set text and anthology poem","Build an argument that answers the question rather than retelling the plot","Connect methods to meanings and relevant context","Practise selecting comparison poems by theme and method","For extracts, analyse the passage and connect it to the whole text"]', 'https://www.aqa.org.uk/subjects/english/gcse/english-literature-8702/specification', 'https://www.aqa.org.uk/subjects/english/gcse/english-literature-8702/assessment-resources', 0, '2026-09-26'),
  ('subject-combined-science', 'AQA Combined Science: Trilogy 8464 Higher: six 1 hour 15 minute papers of 70 marks each, with two Biology, two Chemistry and two Physics papers. Each paper is 16.7% of the double award. Trilogy is the current working course assumption.', '["AO1: demonstrate knowledge and understanding of scientific ideas, techniques and procedures","AO2: apply knowledge and understanding of scientific ideas, enquiry, techniques and procedures","AO3: analyse information and ideas, interpret and evaluate, make judgements and improve procedures"]', '["Revise required practical methods, variables, risks, graphs and evaluation","Learn equations and practise rearranging and substituting with units","Use precise scientific vocabulary in explanations","Practise applying familiar knowledge to unfamiliar contexts","Check the mock or entry code is 8464H; replace this map if 8465H is confirmed"]', 'https://www.aqa.org.uk/subjects/science/gcse/science-8464/specification', 'https://www.aqa.org.uk/subjects/science/gcse/science-8464/assessment-resources', 0, '2026-09-26')
ON CONFLICT(subject_id) DO UPDATE SET
  exam_summary = excluded.exam_summary,
  assessment_objectives_json = excluded.assessment_objectives_json,
  exam_tips_json = excluded.exam_tips_json,
  specification_url = excluded.specification_url,
  assessment_resources_url = excluded.assessment_resources_url,
  provisional = excluded.provisional,
  verified_at = excluded.verified_at,
  updated_at = CURRENT_TIMESTAMP;

DELETE FROM revision_resources
WHERE subject_id IN ('subject-mathematics', 'subject-english-language', 'subject-english-literature', 'subject-combined-science');

INSERT INTO revision_resources
  (id, subject_id, topic_id, title, provider, resource_type, description, url, free_access, sort_order, verified_at)
VALUES
  ('res-maths-aqa-spec', 'subject-mathematics', NULL, 'AQA GCSE Mathematics 8300 specification', 'AQA', 'specification', 'Official Higher-tier content and assessment requirements.', 'https://www.aqa.org.uk/subjects/mathematics/gcse/mathematics-8300/specification', 1, 1, '2026-09-26'),
  ('res-maths-aqa-papers', 'subject-mathematics', NULL, 'Mathematics assessment resources', 'AQA', 'past_papers', 'Official question papers, mark schemes and examiner reports.', 'https://www.aqa.org.uk/subjects/mathematics/gcse/mathematics-8300/assessment-resources', 1, 2, '2026-09-26'),
  ('res-language-aqa-spec', 'subject-english-language', NULL, 'AQA GCSE English Language 8700 specification', 'AQA', 'specification', 'Official reading, writing and Spoken Language requirements.', 'https://www.aqa.org.uk/subjects/english/gcse/english-8700/specification', 1, 1, '2026-09-26'),
  ('res-language-aqa-papers', 'subject-english-language', NULL, 'English Language assessment resources', 'AQA', 'past_papers', 'Official question papers, inserts, mark schemes and examiner reports.', 'https://www.aqa.org.uk/subjects/english/gcse/english-8700/assessment-resources', 1, 2, '2026-09-26'),
  ('res-literature-aqa-spec', 'subject-english-literature', NULL, 'AQA GCSE English Literature 8702 specification', 'AQA', 'specification', 'Official requirements for the selected texts, poetry and unseen poetry.', 'https://www.aqa.org.uk/subjects/english/gcse/english-literature-8702/specification', 1, 1, '2026-09-26'),
  ('res-literature-aqa-papers', 'subject-english-literature', NULL, 'English Literature assessment resources', 'AQA', 'past_papers', 'Official question papers, mark schemes and examiner reports.', 'https://www.aqa.org.uk/subjects/english/gcse/english-literature-8702/assessment-resources', 1, 2, '2026-09-26'),
  ('res-science-aqa-spec', 'subject-combined-science', NULL, 'AQA Combined Science: Trilogy 8464 specification', 'AQA', 'specification', 'Official Higher-tier Biology, Chemistry, Physics and required-practical content.', 'https://www.aqa.org.uk/subjects/science/gcse/science-8464/specification', 1, 1, '2026-09-26'),
  ('res-science-aqa-papers', 'subject-combined-science', NULL, 'Combined Science: Trilogy assessment resources', 'AQA', 'past_papers', 'Official Higher-tier papers, mark schemes and examiner reports.', 'https://www.aqa.org.uk/subjects/science/gcse/science-8464/assessment-resources', 1, 2, '2026-09-26');
