-- Confirmed exam boards and complete specification maps for Geography,
-- Business and Design & Technology. Geography and D&T retain explicit
-- option_required rows until the school confirms the taught choices.
PRAGMA foreign_keys = ON;

INSERT OR IGNORE INTO subjects (id, name, exam_board, specification_code)
VALUES
  ('subject-geography', 'Geography', 'AQA', '8035'),
  ('subject-business', 'Business', 'Edexcel', '1BS0'),
  ('subject-design-technology', 'Design and Technology', 'AQA', '8552');

UPDATE subjects SET exam_board = 'AQA', specification_code = '8035', updated_at = CURRENT_TIMESTAMP WHERE id = 'subject-geography';
UPDATE subjects SET exam_board = 'Edexcel', specification_code = '1BS0', updated_at = CURRENT_TIMESTAMP WHERE id = 'subject-business';
UPDATE subjects SET exam_board = 'AQA', specification_code = '8552', updated_at = CURRENT_TIMESTAMP WHERE id = 'subject-design-technology';

UPDATE student_subjects
SET tier = 'not_applicable',
    options_json = json_set(json_set(json_set(json_set(json_set(options_json,
      '$.configuration', 'confirmed'), '$.livingWorldOption', 'TBC'), '$.ukLandscapeOptions', 'TBC'),
      '$.resourceOption', 'TBC'), '$.caseStudies', 'TBC'),
    updated_at = CURRENT_TIMESTAMP
WHERE subject_id = 'subject-geography';

UPDATE student_subjects
SET tier = 'not_applicable', options_json = json_set(options_json, '$.configuration', 'confirmed'), updated_at = CURRENT_TIMESTAMP
WHERE subject_id = 'subject-business';

UPDATE student_subjects
SET tier = 'not_applicable',
    options_json = json_set(json_set(options_json, '$.configuration', 'confirmed'), '$.specialistMaterial', 'TBC'),
    updated_at = CURRENT_TIMESTAMP
WHERE subject_id = 'subject-design-technology';

UPDATE topics SET active = 0, updated_at = CURRENT_TIMESTAMP
WHERE subject_id IN ('subject-geography', 'subject-business', 'subject-design-technology');

DELETE FROM course_components WHERE subject_id IN ('subject-geography', 'subject-business', 'subject-design-technology');

INSERT INTO course_components
  (id, subject_id, name, component_code, calculator_allowed, duration_minutes, maximum_marks, weighting_percent, tier, sort_order, source_reference)
VALUES
  ('geography-8035-1', 'subject-geography', 'Paper 1: Living with the physical environment', '8035/1', 1, 90, 88, 35, 'both', 1, 'https://www.aqa.org.uk/subjects/geography/gcse/geography-8035/specification/specification-at-a-glance'),
  ('geography-8035-2', 'subject-geography', 'Paper 2: Challenges in the human environment', '8035/2', 1, 90, 88, 35, 'both', 2, 'https://www.aqa.org.uk/subjects/geography/gcse/geography-8035/specification/specification-at-a-glance'),
  ('geography-8035-3', 'subject-geography', 'Paper 3: Geographical applications', '8035/3', 1, 90, 76, 30, 'both', 3, 'https://www.aqa.org.uk/subjects/geography/gcse/geography-8035/specification/specification-at-a-glance'),
  ('business-1bs0-1', 'subject-business', 'Theme 1: Investigating small business', '1BS0/01', 1, 105, 90, 50, 'both', 1, 'https://qualifications.pearson.com/content/dam/pdf/GCSE/Business/2017/specification-and-sample-assessments/gcse-business-spec-2017.pdf'),
  ('business-1bs0-2', 'subject-business', 'Theme 2: Building a business', '1BS0/02', 1, 105, 90, 50, 'both', 2, 'https://qualifications.pearson.com/content/dam/pdf/GCSE/Business/2017/specification-and-sample-assessments/gcse-business-spec-2017.pdf'),
  ('dt-8552-paper', 'subject-design-technology', 'Paper 1', '8552/W', 1, 120, 100, 50, 'both', 1, 'https://www.aqa.org.uk/subjects/design-and-technology/gcse/design-and-technology-8552/specification/specification-at-a-glance'),
  ('dt-8552-nea', 'subject-design-technology', 'Non-exam assessment: substantial design and make task', '8552/C', 0, 2100, 100, 50, 'both', 2, 'https://www.aqa.org.uk/subjects/design-and-technology/gcse/design-and-technology-8552/specification/specification-at-a-glance');

INSERT INTO topics
  (id, subject_id, parent_topic_id, component, name, description, exam_board, specification_code, tier, estimated_effort, importance, source_reference, specification_version, applicability)
VALUES
  -- AQA Geography 8035: compulsory content plus every permitted option.
  ('geo-hazards', 'subject-geography', NULL, 'Paper 1 Section A', 'The challenge of natural hazards', 'Natural, tectonic and weather hazards and climate change.', 'AQA', '8035', 'both', 12, 0, 'https://www.aqa.org.uk/subjects/geography/gcse/geography-8035/specification/subject-content/living-with-the-physical-environment', 'AQA 8035', 'common'),
  ('geo-hazards-risk', 'subject-geography', 'geo-hazards', 'Paper 1 Section A', 'Natural hazard risk', 'Definitions and types of natural hazard; factors affecting risk including vulnerability, capacity, urbanisation and climate change; interpreting hazard distributions.', 'AQA', '8035', 'both', 2, 1, 'https://www.aqa.org.uk/subjects/geography/gcse/geography-8035/specification/subject-content/living-with-the-physical-environment', 'AQA 8035', 'common'),
  ('geo-hazards-tectonic', 'subject-geography', 'geo-hazards', 'Paper 1 Section A', 'Tectonic hazards', 'Plate margins and global distribution; processes and features of earthquakes and volcanoes; contrasting named examples, effects, responses and risk management.', 'AQA', '8035', 'both', 4, 1, 'https://www.aqa.org.uk/subjects/geography/gcse/geography-8035/specification/subject-content/living-with-the-physical-environment', 'AQA 8035', 'common'),
  ('geo-hazards-weather', 'subject-geography', 'geo-hazards', 'Paper 1 Section A', 'Weather hazards', 'Global atmospheric circulation; tropical-storm formation, structure, effects and management; UK weather hazards and a named recent extreme-weather event.', 'AQA', '8035', 'both', 4, 1, 'https://www.aqa.org.uk/subjects/geography/gcse/geography-8035/specification/subject-content/living-with-the-physical-environment', 'AQA 8035', 'common'),
  ('geo-hazards-climate', 'subject-geography', 'geo-hazards', 'Paper 1 Section A', 'Climate change', 'Evidence since the Quaternary; natural and human causes; effects on people and environments; mitigation and adaptation strategies.', 'AQA', '8035', 'both', 3, 1, 'https://www.aqa.org.uk/subjects/geography/gcse/geography-8035/specification/subject-content/living-with-the-physical-environment', 'AQA 8035', 'common'),

  ('geo-living-world', 'subject-geography', NULL, 'Paper 1 Section B', 'The living world', 'Ecosystems, tropical rainforests and the selected hot-desert or cold-environment option.', 'AQA', '8035', 'both', 10, 0, 'https://www.aqa.org.uk/subjects/geography/gcse/geography-8035/specification/subject-content/living-with-the-physical-environment', 'AQA 8035', 'common'),
  ('geo-ecosystems', 'subject-geography', 'geo-living-world', 'Paper 1 Section B', 'Ecosystems', 'Components and interdependence; food chains, food webs and nutrient cycling; change and a named small-scale UK ecosystem; global biome distribution.', 'AQA', '8035', 'both', 3, 1, 'https://www.aqa.org.uk/subjects/geography/gcse/geography-8035/specification/subject-content/living-with-the-physical-environment', 'AQA 8035', 'common'),
  ('geo-rainforests', 'subject-geography', 'geo-living-world', 'Paper 1 Section B', 'Tropical rainforests', 'Climate, soils, plants and animals; causes and impacts of deforestation; a named case study; sustainable management including conservation and international agreements.', 'AQA', '8035', 'both', 4, 1, 'https://www.aqa.org.uk/subjects/geography/gcse/geography-8035/specification/subject-content/living-with-the-physical-environment', 'AQA 8035', 'common'),
  ('geo-hot-deserts', 'subject-geography', 'geo-living-world', 'Paper 1 Section B', 'Hot deserts', 'Characteristics and interdependence; plant and animal adaptations; development opportunities and challenges in a named desert; desertification causes and management.', 'AQA', '8035', 'both', 4, 1, 'https://www.aqa.org.uk/subjects/geography/gcse/geography-8035/specification/subject-content/living-with-the-physical-environment', 'AQA 8035', 'option_required'),
  ('geo-cold-environments', 'subject-geography', 'geo-living-world', 'Paper 1 Section B', 'Cold environments', 'Characteristics and interdependence; adaptations; development opportunities and challenges in a named cold environment; protection and sustainable management.', 'AQA', '8035', 'both', 4, 1, 'https://www.aqa.org.uk/subjects/geography/gcse/geography-8035/specification/subject-content/living-with-the-physical-environment', 'AQA 8035', 'option_required'),

  ('geo-uk-landscapes', 'subject-geography', NULL, 'Paper 1 Section C', 'Physical landscapes in the UK', 'UK landscape overview and two selected landscapes from coasts, rivers and glaciation.', 'AQA', '8035', 'both', 11, 0, 'https://www.aqa.org.uk/subjects/geography/gcse/geography-8035/specification/subject-content/living-with-the-physical-environment', 'AQA 8035', 'common'),
  ('geo-uk-overview', 'subject-geography', 'geo-uk-landscapes', 'Paper 1 Section C', 'UK physical landscape overview', 'Location of major upland and lowland areas; major river systems; links between geology, relief, climate and characteristic UK landscapes.', 'AQA', '8035', 'both', 2, 1, 'https://www.aqa.org.uk/subjects/geography/gcse/geography-8035/specification/subject-content/living-with-the-physical-environment', 'AQA 8035', 'common'),
  ('geo-coasts', 'subject-geography', 'geo-uk-landscapes', 'Paper 1 Section C', 'Coastal landscapes in the UK', 'Wave, weathering, mass-movement, erosion, transport and deposition processes; coastal landforms; a named UK coastline; hard and soft engineering and managed retreat.', 'AQA', '8035', 'both', 5, 1, 'https://www.aqa.org.uk/subjects/geography/gcse/geography-8035/specification/subject-content/living-with-the-physical-environment', 'AQA 8035', 'option_required'),
  ('geo-rivers', 'subject-geography', 'geo-uk-landscapes', 'Paper 1 Section C', 'River landscapes in the UK', 'Long and cross profiles; erosion, transport and deposition; river landforms; flood hydrographs and risk; a named UK river and management strategies.', 'AQA', '8035', 'both', 5, 1, 'https://www.aqa.org.uk/subjects/geography/gcse/geography-8035/specification/subject-content/living-with-the-physical-environment', 'AQA 8035', 'option_required'),
  ('geo-glacial', 'subject-geography', 'geo-uk-landscapes', 'Paper 1 Section C', 'Glacial landscapes in the UK', 'Glacial processes; erosional and depositional landforms; a named UK upland area; tourism, farming and conflict; management strategies.', 'AQA', '8035', 'both', 5, 1, 'https://www.aqa.org.uk/subjects/geography/gcse/geography-8035/specification/subject-content/living-with-the-physical-environment', 'AQA 8035', 'option_required'),

  ('geo-human', 'subject-geography', NULL, 'Paper 2', 'Challenges in the human environment', 'Urban issues, the changing economic world and resource management.', 'AQA', '8035', 'both', 20, 0, 'https://www.aqa.org.uk/subjects/geography/gcse/geography-8035/specification/subject-content/challenges-in-the-human-environment', 'AQA 8035', 'common'),
  ('geo-urban', 'subject-geography', 'geo-human', 'Paper 2 Section A', 'Urban issues and challenges', 'Global urbanisation and megacities; named LIC or NEE and UK city case studies; opportunities, challenges, regeneration, sustainability and transport management.', 'AQA', '8035', 'both', 7, 1, 'https://www.aqa.org.uk/subjects/geography/gcse/geography-8035/specification/subject-content/challenges-in-the-human-environment', 'AQA 8035', 'common'),
  ('geo-economic', 'subject-geography', 'geo-human', 'Paper 2 Section B', 'The changing economic world', 'Development measures and uneven development; strategies to close the gap; a named LIC or NEE case study; structural change, infrastructure and regional inequality in the UK.', 'AQA', '8035', 'both', 7, 1, 'https://www.aqa.org.uk/subjects/geography/gcse/geography-8035/specification/subject-content/challenges-in-the-human-environment', 'AQA 8035', 'common'),
  ('geo-resources-overview', 'subject-geography', 'geo-human', 'Paper 2 Section C', 'Resource management overview', 'Global inequalities in consumption; UK food, water and energy demand and supply; resource security, sustainability and environmental impacts.', 'AQA', '8035', 'both', 3, 1, 'https://www.aqa.org.uk/subjects/geography/gcse/geography-8035/specification/subject-content/challenges-in-the-human-environment', 'AQA 8035', 'common'),
  ('geo-resource-food', 'subject-geography', 'geo-human', 'Paper 2 Section C', 'Food', 'Global food surplus and deficit; causes and impacts of insecurity; increasing supply; a large-scale agricultural scheme and a local sustainable scheme.', 'AQA', '8035', 'both', 4, 1, 'https://www.aqa.org.uk/subjects/geography/gcse/geography-8035/specification/subject-content/challenges-in-the-human-environment', 'AQA 8035', 'option_required'),
  ('geo-resource-water', 'subject-geography', 'geo-human', 'Paper 2 Section C', 'Water', 'Global water surplus and deficit; causes and impacts of insecurity; increasing supply; a large-scale transfer scheme and a local sustainable scheme.', 'AQA', '8035', 'both', 4, 1, 'https://www.aqa.org.uk/subjects/geography/gcse/geography-8035/specification/subject-content/challenges-in-the-human-environment', 'AQA 8035', 'option_required'),
  ('geo-resource-energy', 'subject-geography', 'geo-human', 'Paper 2 Section C', 'Energy', 'Global energy consumption and supply; causes and impacts of insecurity; renewable and non-renewable strategies; fossil-fuel extraction and a local renewable scheme.', 'AQA', '8035', 'both', 4, 1, 'https://www.aqa.org.uk/subjects/geography/gcse/geography-8035/specification/subject-content/challenges-in-the-human-environment', 'AQA 8035', 'option_required'),

  ('geo-applications', 'subject-geography', NULL, 'Paper 3', 'Geographical applications and skills', 'Issue evaluation, fieldwork enquiries and geographical skills assessed across all papers.', 'AQA', '8035', 'both', 10, 0, 'https://www.aqa.org.uk/subjects/geography/gcse/geography-8035/specification/subject-content/geographical-applications', 'AQA 8035', 'common'),
  ('geo-issue-evaluation', 'subject-geography', 'geo-applications', 'Paper 3 Section A', 'Issue evaluation', 'Interpret the pre-release booklet; connect physical and human geography; analyse stakeholders and options; reach a reasoned, evidence-based judgement.', 'AQA', '8035', 'both', 3, 1, 'https://www.aqa.org.uk/subjects/geography/gcse/geography-8035/specification/subject-content/geographical-applications', 'AQA 8035', 'common'),
  ('geo-fieldwork', 'subject-geography', 'geo-applications', 'Paper 3 Section B', 'Fieldwork', 'Two contrasting physical and human enquiries; questions, methods, sampling, data presentation, analysis, conclusions, evaluation and unfamiliar fieldwork.', 'AQA', '8035', 'both', 4, 1, 'https://www.aqa.org.uk/subjects/geography/gcse/geography-8035/specification/subject-content/geographical-applications', 'AQA 8035', 'common'),
  ('geo-skills', 'subject-geography', 'geo-applications', 'All papers', 'Geographical skills', 'OS maps, scale, direction and grid references; graphs, photographs and GIS; numerical and statistical skills; interpreting, analysing and evaluating sources.', 'AQA', '8035', 'both', 4, 1, 'https://www.aqa.org.uk/subjects/geography/gcse/geography-8035/specification/subject-content/geographical-skills', 'AQA 8035', 'common'),

  -- Pearson Edexcel Business 1BS0.
  ('business-theme1', 'subject-business', NULL, 'Paper 1', 'Theme 1: Investigating small business', 'Starting and running a small business in local and national contexts.', 'Edexcel', '1BS0', 'both', 20, 0, 'https://qualifications.pearson.com/content/dam/pdf/GCSE/Business/2017/specification-and-sample-assessments/gcse-business-spec-2017.pdf', 'Issue 2, July 2022', 'common'),
  ('business-1-1-enterprise', 'subject-business', 'business-theme1', 'Paper 1', '1.1 Enterprise and entrepreneurship', 'Dynamic business ideas and obsolescence; risk and reward; enterprise, customer needs, added value and the role and characteristics of entrepreneurs.', 'Edexcel', '1BS0', 'both', 4, 1, 'https://qualifications.pearson.com/content/dam/pdf/GCSE/Business/2017/specification-and-sample-assessments/gcse-business-spec-2017.pdf', 'Issue 2, July 2022', 'common'),
  ('business-1-2-opportunity', 'subject-business', 'business-theme1', 'Paper 1', '1.2 Spotting a business opportunity', 'Customer needs; primary and secondary market research, qualitative and quantitative data and reliability; segmentation, market mapping and competition.', 'Edexcel', '1BS0', 'both', 4, 1, 'https://qualifications.pearson.com/content/dam/pdf/GCSE/Business/2017/specification-and-sample-assessments/gcse-business-spec-2017.pdf', 'Issue 2, July 2022', 'common'),
  ('business-1-3-finance', 'subject-business', 'business-theme1', 'Paper 1', '1.3 Putting a business idea into practice', 'Financial and non-financial objectives; revenue, costs, profit, break-even and margin of safety; cash flow and insolvency; appropriate sources of finance.', 'Edexcel', '1BS0', 'both', 5, 1, 'https://qualifications.pearson.com/content/dam/pdf/GCSE/Business/2017/specification-and-sample-assessments/gcse-business-spec-2017.pdf', 'Issue 2, July 2022', 'common'),
  ('business-1-4-effective', 'subject-business', 'business-theme1', 'Paper 1', '1.4 Making the business effective', 'Ownership, liability and franchising; location decisions; the integrated marketing mix; purposes, contents and limitations of business plans.', 'Edexcel', '1BS0', 'both', 4, 1, 'https://qualifications.pearson.com/content/dam/pdf/GCSE/Business/2017/specification-and-sample-assessments/gcse-business-spec-2017.pdf', 'Issue 2, July 2022', 'common'),
  ('business-1-5-external', 'subject-business', 'business-theme1', 'Paper 1', '1.5 Understanding external influences', 'Stakeholders and conflict; business technology; consumer and employment law; unemployment, income, inflation, interest, taxation and exchange rates; business responses.', 'Edexcel', '1BS0', 'both', 4, 1, 'https://qualifications.pearson.com/content/dam/pdf/GCSE/Business/2017/specification-and-sample-assessments/gcse-business-spec-2017.pdf', 'Issue 2, July 2022', 'common'),

  ('business-theme2', 'subject-business', NULL, 'Paper 2', 'Theme 2: Building a business', 'Growing a business in national and global contexts.', 'Edexcel', '1BS0', 'both', 20, 0, 'https://qualifications.pearson.com/content/dam/pdf/GCSE/Business/2017/specification-and-sample-assessments/gcse-business-spec-2017.pdf', 'Issue 2, July 2022', 'common'),
  ('business-2-1-growth', 'subject-business', 'business-theme2', 'Paper 2', '2.1 Growing the business', 'Internal and external growth, ownership and finance; changing objectives; globalisation and international competition; ethical and environmental trade-offs.', 'Edexcel', '1BS0', 'both', 4, 1, 'https://qualifications.pearson.com/content/dam/pdf/GCSE/Business/2017/specification-and-sample-assessments/gcse-business-spec-2017.pdf', 'Issue 2, July 2022', 'common'),
  ('business-2-2-marketing', 'subject-business', 'business-theme2', 'Paper 2', '2.2 Making marketing decisions', 'Design mix and product life cycle; pricing and promotion strategies; distribution; integration of product, price, promotion and place for competitive advantage.', 'Edexcel', '1BS0', 'both', 4, 1, 'https://qualifications.pearson.com/content/dam/pdf/GCSE/Business/2017/specification-and-sample-assessments/gcse-business-spec-2017.pdf', 'Issue 2, July 2022', 'common'),
  ('business-2-3-operations', 'subject-business', 'business-theme2', 'Paper 2', '2.3 Making operational decisions', 'Job, batch and flow production; technology, productivity, quality and flexibility; stock, JIT, procurement and logistics; quality and customer service.', 'Edexcel', '1BS0', 'both', 4, 1, 'https://qualifications.pearson.com/content/dam/pdf/GCSE/Business/2017/specification-and-sample-assessments/gcse-business-spec-2017.pdf', 'Issue 2, July 2022', 'common'),
  ('business-2-4-finance', 'subject-business', 'business-theme2', 'Paper 2', '2.4 Making financial decisions', 'Gross and net profit; gross and net profit margins; average rate of return; interpretation and limitations of financial, marketing and market data.', 'Edexcel', '1BS0', 'both', 4, 1, 'https://qualifications.pearson.com/content/dam/pdf/GCSE/Business/2017/specification-and-sample-assessments/gcse-business-spec-2017.pdf', 'Issue 2, July 2022', 'common'),
  ('business-2-5-people', 'subject-business', 'business-theme2', 'Paper 2', '2.5 Making human resource decisions', 'Organisational structures and communication; recruitment and training; financial and non-financial motivation; effects on retention and productivity.', 'Edexcel', '1BS0', 'both', 4, 1, 'https://qualifications.pearson.com/content/dam/pdf/GCSE/Business/2017/specification-and-sample-assessments/gcse-business-spec-2017.pdf', 'Issue 2, July 2022', 'common'),

  -- AQA Design & Technology 8552.
  ('dt-core', 'subject-design-technology', NULL, 'Paper 1 Section A', 'Core technical principles', 'Breadth of technical knowledge required for every student.', 'AQA', '8552', 'both', 18, 0, 'https://www.aqa.org.uk/subjects/design-and-technology/gcse/design-and-technology-8552/specification/subject-content/core-technical-principles', 'AQA 8552', 'common'),
  ('dt-emerging', 'subject-design-technology', 'dt-core', 'Paper 1 Section A', 'New and emerging technologies', 'Automation, robotics, flexible manufacturing and systems; enterprise and crowdfunding; people, society, culture, environment, sustainability and planned obsolescence.', 'AQA', '8552', 'both', 4, 1, 'https://www.aqa.org.uk/subjects/design-and-technology/gcse/design-and-technology-8552/specification/subject-content/core-technical-principles', 'AQA 8552', 'common'),
  ('dt-energy', 'subject-design-technology', 'dt-core', 'Paper 1 Section A', 'Energy generation and storage', 'Fossil fuels, nuclear and renewable generation; arguments for and against sources; batteries, kinetic storage and energy-system selection.', 'AQA', '8552', 'both', 3, 1, 'https://www.aqa.org.uk/subjects/design-and-technology/gcse/design-and-technology-8552/specification/subject-content/core-technical-principles', 'AQA 8552', 'common'),
  ('dt-new-materials', 'subject-design-technology', 'dt-core', 'Paper 1 Section A', 'Developments in new materials', 'Modern, smart, composite and technical textiles; properties and applications; evaluating functional benefit, cost and sustainability.', 'AQA', '8552', 'both', 3, 1, 'https://www.aqa.org.uk/subjects/design-and-technology/gcse/design-and-technology-8552/specification/subject-content/core-technical-principles', 'AQA 8552', 'common'),
  ('dt-systems', 'subject-design-technology', 'dt-core', 'Paper 1 Section A', 'Systems approach to designing', 'Inputs, processes and outputs; electronic components and programmable control; sensors, feedback and block diagrams; selecting subsystems for a function.', 'AQA', '8552', 'both', 4, 1, 'https://www.aqa.org.uk/subjects/design-and-technology/gcse/design-and-technology-8552/specification/subject-content/core-technical-principles', 'AQA 8552', 'common'),
  ('dt-mechanisms', 'subject-design-technology', 'dt-core', 'Paper 1 Section A', 'Mechanical devices', 'Types of motion; levers, linkages, cams, gears and pulleys; changing magnitude and direction; mechanical advantage and suitable applications.', 'AQA', '8552', 'both', 3, 1, 'https://www.aqa.org.uk/subjects/design-and-technology/gcse/design-and-technology-8552/specification/subject-content/core-technical-principles', 'AQA 8552', 'common'),
  ('dt-materials-overview', 'subject-design-technology', 'dt-core', 'Paper 1 Section A', 'Materials and working properties', 'Categories and common types of papers and boards, timbers, metals, polymers and textiles; physical and working properties; selecting materials for use.', 'AQA', '8552', 'both', 4, 1, 'https://www.aqa.org.uk/subjects/design-and-technology/gcse/design-and-technology-8552/specification/subject-content/core-technical-principles', 'AQA 8552', 'common'),

  ('dt-specialist', 'subject-design-technology', NULL, 'Paper 1 Section B', 'Specialist technical principles', 'Principles studied in depth through at least one material category or system.', 'AQA', '8552', 'both', 20, 0, 'https://www.aqa.org.uk/subjects/design-and-technology/gcse/design-and-technology-8552/specification/subject-content/specialist-technical-principles', 'AQA 8552', 'common'),
  ('dt-selection-forces', 'subject-design-technology', 'dt-specialist', 'Paper 1 Section B', 'Material selection, forces and stresses', 'Functional, aesthetic, environmental, availability and cost factors; tension, compression, bending, torsion and shear; reinforcement, stiffening and flexibility.', 'AQA', '8552', 'both', 4, 1, 'https://www.aqa.org.uk/subjects/design-and-technology/gcse/design-and-technology-8552/specification/subject-content/specialist-technical-principles', 'AQA 8552', 'common'),
  ('dt-footprint-origins', 'subject-design-technology', 'dt-specialist', 'Paper 1 Section B', 'Ecological footprint and material origins', 'Extraction and processing from primary sources; product miles and carbon; social impacts and safe work; life-cycle assessment and the six Rs.', 'AQA', '8552', 'both', 4, 1, 'https://www.aqa.org.uk/subjects/design-and-technology/gcse/design-and-technology-8552/specification/subject-content/specialist-technical-principles', 'AQA 8552', 'common'),
  ('dt-working-materials', 'subject-design-technology', 'dt-specialist', 'Paper 1 Section B', 'Working with materials', 'Specialist properties and commercial applications; modifying properties; cutting, abrasion, addition, deforming and reforming processes for the selected material area.', 'AQA', '8552', 'both', 5, 1, 'https://www.aqa.org.uk/subjects/design-and-technology/gcse/design-and-technology-8552/specification/subject-content/specialist-technical-principles', 'AQA 8552', 'option_required'),
  ('dt-production', 'subject-design-technology', 'dt-specialist', 'Paper 1 Section B', 'Stock forms and scales of production', 'Commercial stock forms, types and sizes; calculating quantities; one-off, batch and mass or continuous production; choosing processes for volume and cost.', 'AQA', '8552', 'both', 4, 1, 'https://www.aqa.org.uk/subjects/design-and-technology/gcse/design-and-technology-8552/specification/subject-content/specialist-technical-principles', 'AQA 8552', 'common'),
  ('dt-processes-quality', 'subject-design-technology', 'dt-specialist', 'Paper 1 Section B', 'Specialist processes, quality and finishes', 'Templates, jigs and patterns; specialist tools and commercial processes; tolerances; measurable quality control; preparation, treatments and finishes.', 'AQA', '8552', 'both', 5, 1, 'https://www.aqa.org.uk/subjects/design-and-technology/gcse/design-and-technology-8552/specification/subject-content/specialist-technical-principles', 'AQA 8552', 'option_required'),

  ('dt-designing-making', 'subject-design-technology', NULL, 'Paper 1 Section C and NEA', 'Designing and making principles', 'The iterative process of investigating, designing, developing, making and evaluating.', 'AQA', '8552', 'both', 22, 0, 'https://www.aqa.org.uk/subjects/design-and-technology/gcse/design-and-technology-8552/specification/subject-content/designing-and-making-principles', 'AQA 8552', 'common'),
  ('dt-investigation', 'subject-design-technology', 'dt-designing-making', 'Paper 1 Section C and NEA', 'Investigation and design possibilities', 'Primary and secondary research; user needs and context; product analysis; environmental, social and economic challenges; work of designers and companies.', 'AQA', '8552', 'both', 4, 1, 'https://www.aqa.org.uk/subjects/design-and-technology/gcse/design-and-technology-8552/specification/subject-content/designing-and-making-principles', 'AQA 8552', 'common'),
  ('dt-brief-specification', 'subject-design-technology', 'dt-designing-making', 'Paper 1 Section C and NEA', 'Design brief and specification', 'Turning research into a focused brief; measurable user-centred specification criteria; constraints, function, aesthetics, cost, safety and sustainability.', 'AQA', '8552', 'both', 3, 1, 'https://www.aqa.org.uk/subjects/design-and-technology/gcse/design-and-technology-8552/specification/subject-content/designing-and-making-principles', 'AQA 8552', 'common'),
  ('dt-ideas', 'subject-design-technology', 'dt-designing-making', 'Paper 1 Section C and NEA', 'Generating and communicating ideas', 'Iterative and collaborative strategies; avoiding design fixation; annotated sketches, modelling, CAD and technical communication for different audiences.', 'AQA', '8552', 'both', 4, 1, 'https://www.aqa.org.uk/subjects/design-and-technology/gcse/design-and-technology-8552/specification/subject-content/designing-and-making-principles', 'AQA 8552', 'common'),
  ('dt-development', 'subject-design-technology', 'dt-designing-making', 'Paper 1 Section C and NEA', 'Developing design ideas', 'Using modelling, testing and user feedback; selecting materials and components; resolving dimensions, construction, manufacture and sustainability iteratively.', 'AQA', '8552', 'both', 4, 1, 'https://www.aqa.org.uk/subjects/design-and-technology/gcse/design-and-technology-8552/specification/subject-content/designing-and-making-principles', 'AQA 8552', 'common'),
  ('dt-making', 'subject-design-technology', 'dt-designing-making', 'Paper 1 Section C and NEA', 'Realising design ideas', 'Production planning; material management and minimising waste; accurate marking out; safe tools and processes; tolerances and manufacturing a quality prototype.', 'AQA', '8552', 'both', 5, 1, 'https://www.aqa.org.uk/subjects/design-and-technology/gcse/design-and-technology-8552/specification/subject-content/designing-and-making-principles', 'AQA 8552', 'common'),
  ('dt-evaluation', 'subject-design-technology', 'dt-designing-making', 'Paper 1 Section C and NEA', 'Analysing and evaluating', 'Testing against measurable criteria; user and third-party feedback; analysing data; identifying improvements; evaluating social, environmental and commercial viability.', 'AQA', '8552', 'both', 4, 1, 'https://www.aqa.org.uk/subjects/design-and-technology/gcse/design-and-technology-8552/specification/subject-content/designing-and-making-principles', 'AQA 8552', 'common');

INSERT INTO subject_revision_guides
  (subject_id, exam_summary, assessment_objectives_json, exam_tips_json, specification_url, assessment_resources_url, provisional, verified_at)
VALUES
  ('subject-geography', 'AQA GCSE Geography 8035: Paper 1 Living with the physical environment (1 hour 30 minutes, 88 marks, 35%); Paper 2 Challenges in the human environment (1 hour 30 minutes, 88 marks, 35%); Paper 3 Geographical applications (1 hour 30 minutes, 76 marks, 30%). Optional units and named case studies still need confirming.', '["AO1: demonstrate knowledge of locations, places, processes, environments and scales","AO2: show geographical understanding of concepts and interrelationships","AO3: apply knowledge and understanding to interpret, analyse and evaluate information and issues","AO4: select, adapt and use geographical skills and techniques"]', '["Learn precise named-case-study evidence rather than generic stories","Develop process chains using because, therefore and this means","Use figures, units and map or graph evidence whenever a resource is supplied","For evaluate or assess questions, compare alternatives and finish with a supported judgement","Practise fieldwork methods, limitations, conclusions and improvements for both enquiries"]', 'https://www.aqa.org.uk/subjects/geography/gcse/geography-8035/specification', 'https://www.aqa.org.uk/subjects/geography/gcse/geography-8035/assessment-resources', 1, '2026-09-28'),
  ('subject-business', 'Pearson Edexcel GCSE Business 1BS0: Paper 1 Investigating small business and Paper 2 Building a business are each 1 hour 45 minutes, 90 marks and 50%. Both include calculations, multiple-choice, short-answer and extended-writing questions; calculators are allowed.', '["AO1: demonstrate knowledge and understanding of business concepts and issues","AO2: apply knowledge and understanding to business contexts","AO3: analyse business information and issues to show chains of impact","AO4: evaluate information and issues to make justified conclusions"]', '["Apply each point to the exact business, objective and data in the source","Show formula, substitution, working and units for calculations","Develop analysis through connected because and therefore chains","For justify and evaluate questions, compare realistic options and make a conditional judgement","Learn all required formulae because they are not supplied in the examination"]', 'https://qualifications.pearson.com/content/dam/pdf/GCSE/Business/2017/specification-and-sample-assessments/gcse-business-spec-2017.pdf', 'https://qualifications.pearson.com/en/qualifications/edexcel-gcses/business-2017.coursematerials.html', 0, '2026-09-28'),
  ('subject-design-technology', 'AQA GCSE Design and Technology 8552: a 2-hour, 100-mark written paper worth 50% and a substantial design-and-make NEA of approximately 30–35 hours, 100 marks and 50%. The paper assesses core, specialist, and designing and making principles; the specialist material area still needs confirming.', '["AO1: identify, investigate and outline design possibilities to address needs and wants","AO2: design and make prototypes that are fit for purpose","AO3: analyse and evaluate design decisions and outcomes, including the work of others","AO4: demonstrate and apply technical knowledge and understanding"]', '["Connect every design choice to a named user need and measurable specification point","Justify material and process choices through properties, scale, cost and sustainability","Show calculations clearly: at least 15% of the paper assesses maths and at least 10% assesses science","Use testing evidence to drive iterations instead of describing changes","Practise extended responses that compare trade-offs and reach a justified conclusion"]', 'https://www.aqa.org.uk/subjects/design-and-technology/gcse/design-and-technology-8552/specification', 'https://www.aqa.org.uk/subjects/design-and-technology/gcse/design-and-technology-8552/assessment-resources', 1, '2026-09-28')
ON CONFLICT(subject_id) DO UPDATE SET
  exam_summary = excluded.exam_summary,
  assessment_objectives_json = excluded.assessment_objectives_json,
  exam_tips_json = excluded.exam_tips_json,
  specification_url = excluded.specification_url,
  assessment_resources_url = excluded.assessment_resources_url,
  provisional = excluded.provisional,
  verified_at = excluded.verified_at,
  updated_at = CURRENT_TIMESTAMP;

DELETE FROM revision_resources WHERE subject_id IN ('subject-geography', 'subject-business', 'subject-design-technology');

INSERT INTO revision_resources
  (id, subject_id, topic_id, title, provider, resource_type, description, url, free_access, sort_order, verified_at)
VALUES
  ('res-geo-aqa-spec', 'subject-geography', NULL, 'AQA GCSE Geography 8035 specification', 'AQA', 'specification', 'Official subject content, assessment structure and geographical skills.', 'https://www.aqa.org.uk/subjects/geography/gcse/geography-8035/specification', 1, 1, '2026-09-28'),
  ('res-geo-aqa-papers', 'subject-geography', NULL, 'Geography assessment resources', 'AQA', 'past_papers', 'Official question papers, mark schemes, inserts and examiner reports.', 'https://www.aqa.org.uk/subjects/geography/gcse/geography-8035/assessment-resources', 1, 2, '2026-09-28'),
  ('res-geo-bbc', 'subject-geography', NULL, 'AQA GCSE Geography revision', 'BBC Bitesize', 'lesson', 'AQA-aligned revision guides, explanations and practice across the course.', 'https://www.bbc.co.uk/bitesize/examspecs/zy3ptyc', 1, 3, '2026-09-28'),
  ('res-geo-internet-geography', 'subject-geography', NULL, 'AQA GCSE Geography revision', 'Internet Geography', 'lesson', 'Topic revision, case-study support, quizzes and revision guidance for AQA Geography.', 'https://www.internetgeography.net/gcse-geography-revision/', 1, 4, '2026-09-28'),
  ('res-business-edexcel-spec', 'subject-business', NULL, 'Edexcel GCSE Business 1BS0 specification', 'Pearson Edexcel', 'specification', 'Official Theme 1 and Theme 2 content, assessment objectives and formulae.', 'https://qualifications.pearson.com/content/dam/pdf/GCSE/Business/2017/specification-and-sample-assessments/gcse-business-spec-2017.pdf', 1, 1, '2026-09-28'),
  ('res-business-edexcel-papers', 'subject-business', NULL, 'Business course materials', 'Pearson Edexcel', 'past_papers', 'Official sample and past assessment materials, mark schemes and support.', 'https://qualifications.pearson.com/en/qualifications/edexcel-gcses/business-2017.coursematerials.html', 1, 2, '2026-09-28'),
  ('res-dt-aqa-spec', 'subject-design-technology', NULL, 'AQA GCSE Design and Technology 8552 specification', 'AQA', 'specification', 'Official core, specialist, designing and making, and NEA requirements.', 'https://www.aqa.org.uk/subjects/design-and-technology/gcse/design-and-technology-8552/specification', 1, 1, '2026-09-28'),
  ('res-dt-aqa-papers', 'subject-design-technology', NULL, 'Design and Technology assessment resources', 'AQA', 'past_papers', 'Official question papers, mark schemes and NEA guidance.', 'https://www.aqa.org.uk/subjects/design-and-technology/gcse/design-and-technology-8552/assessment-resources', 1, 2, '2026-09-28');
