import type { Analytics } from '../types'
import { BurndownChart } from './BurndownChart'

interface Props { analytics: Analytics; onNavigate: (view: 'analytics' | 'courses' | 'calendar' | 'subjects') => void }
export function ParentDashboard({ analytics, onNavigate }: Props) {
  const labels = { on_track: 'On track', slightly_behind: 'Slightly behind', needs_attention: 'Needs attention' }
  return <section aria-labelledby="parent-heading">
    <div className={`parent-status parent-status--${analytics.onTrack} card`}><div><p className="eyebrow">Parent overview</p><h2 id="parent-heading">{labels[analytics.onTrack]}</h2><p>See whether revision happened, what is improving and the most useful next step.</p></div><div className="parent-actions"><button onClick={() => onNavigate('subjects')} type="button">Review subject evidence</button><button className="secondary" onClick={() => onNavigate('analytics')} type="button">Open full analytics</button></div></div>
    <div className="dashboard-stats"><article className="mini-stat"><strong>{analytics.week.completedSessions}/{analytics.week.plannedSessions}</strong><span>sessions this week</span></article><article className="mini-stat"><strong>{analytics.week.completedMinutes}/{analytics.week.plannedMinutes}m</strong><span>minutes this week</span></article><article className="mini-stat"><strong>{analytics.overall.coverage}%</strong><span>coverage</span></article><article className="mini-stat"><strong>{analytics.overall.mastery ?? '—'}{analytics.overall.mastery === null ? '' : '%'}</strong><span>mastery</span></article></div>
    <div className="analytics-grid"><article className="card analytics-card"><h3>Overall burndown</h3><BurndownChart points={analytics.burndown} /></article><article className="card analytics-card"><h3>Top weak topics</h3><div className="parent-weak-list">{analytics.weakTopics.map((topic) => <div key={topic.topicId}><span className={`rag-dot rag-dot--${topic.ragStatus}`} /><span><strong>{topic.topicName}</strong><small>{topic.subjectName} · {topic.mastery ?? 'No'} mastery · {topic.workloadRemaining} units left</small></span></div>)}</div></article></div>
    <div className="subject-summary-table" role="table" aria-label="Subject progress"><div className="table-row table-head" role="row"><span>Subject</span><span>Coverage</span><span>Mastery</span><span>Workload</span><span>Consistency</span></div>{analytics.subjects.map((subject) => <div className="table-row" role="row" key={subject.subjectId}><strong>{subject.subjectName}</strong><span>{subject.coverage}%</span><span>{subject.mastery ?? '—'}{subject.mastery === null ? '' : '%'}</span><span>{subject.workloadRemaining}</span><span>{subject.consistency}%</span></div>)}</div>
    <div className="analytics-grid"><article className="card analytics-card"><h3>Next seven days</h3>{analytics.nextSevenDays.length ? <ul className="simple-list">{analytics.nextSevenDays.map((item) => <li key={item.id}><strong>{item.subjectName}</strong><span>{item.topicName} · {item.minutes} min · {new Intl.DateTimeFormat('en-GB', { weekday: 'short', day: 'numeric', month: 'short' }).format(new Date(item.scheduledAt))}</span></li>)}</ul> : <p>No planned workload.</p>}</article><article className="card analytics-card"><h3>Administration</h3><div className="admin-links"><button onClick={() => onNavigate('courses')} type="button">Course configuration</button><button onClick={() => onNavigate('calendar')} type="button">Availability and calendar</button></div><p>{analytics.exams.length} upcoming exams · {analytics.exceptions.length} upcoming exceptions</p></article></div>
  </section>
}
