import { useState } from 'react'
import type { Analytics } from '../types'
import { BurndownChart } from './BurndownChart'
import { formatProductDate } from '../utils/dateTime'

interface Props { analytics: Analytics; onNavigate: (view: 'analytics' | 'courses' | 'calendar' | 'subjects') => void; onResetProgress: (confirmation: string) => Promise<void>; onExport: () => Promise<void>; onAiMarking: (enabled: boolean) => Promise<void> }
export function ParentDashboard({ analytics, onNavigate, onResetProgress, onExport, onAiMarking }: Props) {
  const [resetOpen, setResetOpen] = useState(false)
  const [confirmation, setConfirmation] = useState('')
  const [resetting, setResetting] = useState(false)
  const labels = { not_enough_evidence: 'Ready to get started', on_track: 'On track', slightly_behind: 'Slightly behind', needs_attention: 'Needs attention' }
  async function resetProgress() {
    setResetting(true)
    try { await onResetProgress(confirmation); setResetOpen(false); setConfirmation('') }
    finally { setResetting(false) }
  }
  return <section aria-labelledby="parent-heading">
    <div className={`parent-status parent-status--${analytics.onTrack} card`}><div><p className="eyebrow">Parent overview</p><h2 id="parent-heading">{labels[analytics.onTrack]}</h2><p>{analytics.onTrack === 'not_enough_evidence' ? 'Complete a few short checks before the app judges progress. The first plan is ready without labelling a new learner as behind.' : 'See whether revision happened, what is improving and the most useful next step.'}</p></div><div className="parent-actions"><button onClick={() => onNavigate('subjects')} type="button">Review subject evidence</button><button className="secondary" onClick={() => onNavigate('analytics')} type="button">Open full analytics</button></div></div>
    <div className="dashboard-stats"><article className="mini-stat"><strong>{analytics.week.completedSessions}/{analytics.week.plannedSessions}</strong><span>sessions this week</span></article><article className="mini-stat"><strong>{analytics.week.completedMinutes}/{analytics.week.plannedMinutes}m</strong><span>minutes this week</span></article><article className="mini-stat"><strong>{analytics.overall.coverage}%</strong><span>coverage</span></article><article className="mini-stat"><strong>{analytics.overall.mastery ?? '—'}{analytics.overall.mastery === null ? '' : '%'}</strong><span>mastery</span></article></div>
    <div className="analytics-grid"><article className="card analytics-card"><h3>Overall burndown</h3><BurndownChart points={analytics.burndown} /></article><article className="card analytics-card"><h3>Top weak topics</h3><div className="parent-weak-list">{analytics.weakTopics.map((topic) => <div key={topic.topicId}><span className={`rag-dot rag-dot--${topic.ragStatus}`} /><span><strong>{topic.topicName}</strong><small>{topic.subjectName} · {topic.mastery ?? 'No'} mastery estimate · about {topic.workloadRemaining} sessions left</small></span></div>)}</div>{!analytics.weakTopics.length ? <p>No weak topics yet. Checks completed in the app will build this list.</p> : null}</article></div>
    <div aria-label="Subject progress table" className="subject-summary-table" role="region" tabIndex={0}><table><caption>Subject progress</caption><thead><tr><th scope="col">Subject</th><th scope="col">Coverage</th><th scope="col">Mastery</th><th scope="col">Workload</th><th scope="col">Consistency</th></tr></thead><tbody>{analytics.subjects.map((subject) => <tr key={subject.subjectId}><th scope="row">{subject.subjectName}</th><td>{subject.coverage}%</td><td>{subject.mastery ?? '—'}{subject.mastery === null ? '' : '%'}</td><td>{subject.workloadRemaining}</td><td>{subject.consistency}%</td></tr>)}</tbody></table></div>
    <div className="analytics-grid"><article className="card analytics-card"><h3>Next seven days</h3>{analytics.nextSevenDays.length ? <ul className="simple-list">{analytics.nextSevenDays.map((item) => <li key={item.id}><strong>{item.subjectName}</strong><span>{item.topicName} · {item.minutes} min · {formatProductDate(item.scheduledAt, { weekday: 'short', day: 'numeric', month: 'short' })}</span></li>)}</ul> : <p>No planned workload.</p>}</article><article className="card analytics-card"><h3>Administration</h3><div className="admin-links"><button onClick={() => onNavigate('courses')} type="button">Course configuration</button><button onClick={() => onNavigate('calendar')} type="button">Availability and calendar</button><button className="secondary" onClick={() => void onExport()} type="button">Download Student data</button></div><p>{analytics.exams.length} upcoming exams · {analytics.exceptions.length} upcoming exceptions</p><p className={analytics.integrity.ok ? 'success' : 'error'}>{analytics.integrity.ok ? 'Data consistency checks passed.' : `Data check needs attention: ${analytics.integrity.stalledCompletions} stalled saves, ${analytics.integrity.masteryMismatches} mastery mismatches${analytics.integrity.xpMatchesEvents ? '' : ', XP mismatch'}.`}</p><button className="danger-button" onClick={() => setResetOpen(true)} type="button">Reset POC revision progress</button>{resetOpen ? <div className="reset-progress-panel"><h4>Clear all trial activity?</h4><p>This removes lesson history, scores, mastery, notes and XP, then creates a fresh plan. Accounts, courses, tutors, exams and availability remain.</p><label>Type <strong>RESET PROGRESS</strong> to confirm<input autoComplete="off" onChange={(event) => setConfirmation(event.target.value)} value={confirmation} /></label><div><button className="secondary" onClick={() => { setResetOpen(false); setConfirmation('') }} type="button">Cancel</button><button className="danger-button" disabled={confirmation !== 'RESET PROGRESS' || resetting} onClick={() => void resetProgress()} type="button">{resetting ? 'Resetting…' : 'Clear trial activity'}</button></div></div> : null}</article></div>
    <article className="card ai-control"><div><p className="eyebrow">Parent control</p><h3>Optional AI marking</h3><p>{analytics.aiMarkingEnabled ? 'Enabled. The Student still sees a disclosure and must opt in before each transfer.' : 'Off. Written practice, exemplars and self-checks remain available without sending work to an AI provider.'}</p></div><button className={analytics.aiMarkingEnabled ? 'secondary' : undefined} onClick={() => void onAiMarking(!analytics.aiMarkingEnabled)} type="button">{analytics.aiMarkingEnabled ? 'Turn AI marking off' : 'Enable optional AI marking'}</button></article>
  </section>
}
